"""
英検2級 全単語チャレンジ カリキュラム生成スクリプト
- 1日20語 × 75日 = 1,500語
- テーマ別に整理（動詞、形容詞、名詞、熟語等）
- 出力: data.js（window.CURRICULUM を定義）
"""

import json
from pathlib import Path

# ============================================================
# Word entry helper
# ============================================================
def W(en, pos, ja, ex_en, ex_ja):
    return {"en": en, "pos": pos, "ja": ja, "ex_en": ex_en, "ex_ja": ex_ja}


# ============================================================
# 動詞（重要動詞 300語） - Days 1-15
# ============================================================
VERBS = [
    # Day 1: 基本動作・移動
    W("achieve","動","達成する","She achieved her goal.","彼女は目標を達成した。"),
    W("acquire","動","獲得する、習得する","He acquired a new skill.","彼は新しい技術を習得した。"),
    W("admit","動","認める、入学を許可する","I admit my mistake.","自分の間違いを認める。"),
    W("adopt","動","採用する、養子にする","They adopted a new policy.","彼らは新方針を採用した。"),
    W("advance","動","前進する、進歩する","Science advances rapidly.","科学は急速に進歩する。"),
    W("affect","動","影響を与える","Weather affects mood.","天気は気分に影響する。"),
    W("afford","動","余裕がある","I can't afford a car.","車を買う余裕がない。"),
    W("announce","動","発表する、知らせる","They announced the winner.","勝者を発表した。"),
    W("apply","動","申し込む、適用する","Apply for the job.","その仕事に応募して。"),
    W("approach","動/名","近づく/方法","He approached the door.","彼はドアに近づいた。"),
    W("approve","動","賛成する、承認する","The boss approved the plan.","上司が計画を承認した。"),
    W("argue","動","議論する、主張する","They argued about money.","彼らはお金で言い争った。"),
    W("arrange","動","手配する、整える","I arranged the meeting.","会議を手配した。"),
    W("assume","動","仮定する、引き受ける","I assume you are right.","あなたが正しいと思う。"),
    W("attempt","動/名","試みる/試み","He attempted to climb.","彼は登ろうと試みた。"),
    W("attract","動","引きつける","Flowers attract bees.","花は蜂を引きつける。"),
    W("avoid","動","避ける","Avoid crowded places.","混雑した場所を避けて。"),
    W("base","動/名","基づく/基礎","The story is based on truth.","話は事実に基づく。"),
    W("behave","動","振る舞う","Behave yourself.","行儀よくしなさい。"),
    W("belong","動","所属する、〜のもの","I belong to the club.","私はクラブに所属している。"),

    # Day 2: 思考・判断・コミュニケーション
    W("blame","動","責める","Don't blame yourself.","自分を責めないで。"),
    W("boil","動","沸騰させる、ゆでる","Boil the water first.","まず水を沸かして。"),
    W("breathe","動","呼吸する","Breathe deeply.","深く呼吸して。"),
    W("burst","動","破裂する、急に〜する","The balloon burst.","風船が割れた。"),
    W("celebrate","動","祝う","We celebrated her birthday.","彼女の誕生日を祝った。"),
    W("challenge","動/名","挑戦する/挑戦","Challenge yourself daily.","毎日自分に挑戦して。"),
    W("collect","動","集める","I collect stamps.","切手を集めている。"),
    W("communicate","動","伝える、通信する","Communicate clearly.","明確に伝えて。"),
    W("compare","動","比較する","Compare the two prices.","2つの値段を比べて。"),
    W("complain","動","不平を言う","Don't complain so much.","そんなに不平を言わないで。"),
    W("complete","動/形","完成させる/完全な","Complete the form.","用紙に記入して。"),
    W("concern","動/名","関係する/心配","It concerns me a lot.","それは私を心配させる。"),
    W("conclude","動","結論を出す、終える","Let me conclude my speech.","話を終わらせて。"),
    W("confirm","動","確認する","Please confirm your booking.","予約を確認してください。"),
    W("connect","動","つなぐ","Connect the cable here.","ここにケーブルをつないで。"),
    W("consider","動","考慮する","Consider all options.","全ての選択肢を考えて。"),
    W("consist","動","〜から成る","Water consists of H and O.","水はHとOから成る。"),
    W("consume","動","消費する","Cars consume fuel.","車は燃料を消費する。"),
    W("contain","動","含む","This drink contains sugar.","この飲み物は砂糖を含む。"),
    W("contribute","動","貢献する、寄付する","He contributes to society.","彼は社会に貢献している。"),

    # Day 3: 行動・状態変化
    W("convince","動","納得させる","She convinced me to go.","彼女は私を行くよう説得した。"),
    W("cooperate","動","協力する","Let's cooperate together.","一緒に協力しよう。"),
    W("create","動","創造する、生み出す","Create something new.","何か新しいものを作って。"),
    W("damage","動/名","損害を与える/損害","The storm damaged houses.","嵐で家が損害を受けた。"),
    W("deal","動","扱う、取引する","Deal with the problem.","問題に対処して。"),
    W("declare","動","宣言する、申告する","He declared his love.","彼は愛を告白した。"),
    W("decrease","動/名","減少する/減少","Sales decreased last year.","昨年売上が減った。"),
    W("defeat","動/名","負かす/敗北","They defeated the rival.","ライバルを破った。"),
    W("defend","動","守る、弁護する","Defend your country.","国を守れ。"),
    W("delay","動/名","遅らせる/遅れ","The train was delayed.","電車が遅れた。"),
    W("deliver","動","配達する、述べる","Deliver the package.","荷物を届けて。"),
    W("demand","動/名","要求する/要求","Workers demanded a raise.","労働者は昇給を要求した。"),
    W("deny","動","否定する","He denied the rumor.","彼は噂を否定した。"),
    W("depend","動","頼る、〜次第","It depends on you.","あなた次第だ。"),
    W("describe","動","描写する、説明する","Describe the picture.","絵を説明して。"),
    W("deserve","動","〜に値する","You deserve a break.","休む価値があるよ。"),
    W("destroy","動","破壊する","The fire destroyed the house.","火事が家を破壊した。"),
    W("develop","動","発達させる、開発する","Develop new ideas.","新しい考えを発展させて。"),
    W("disappear","動","消える","The cat disappeared suddenly.","猫が突然消えた。"),
    W("discover","動","発見する","Columbus discovered America.","コロンブスがアメリカを発見した。"),

    # Day 4: 思考・感情
    W("discuss","動","議論する","Let's discuss the plan.","計画を話し合おう。"),
    W("divide","動","分ける","Divide the cake into six.","ケーキを6つに分けて。"),
    W("doubt","動/名","疑う/疑い","I doubt his story.","彼の話を疑う。"),
    W("earn","動","稼ぐ、得る","He earns a lot of money.","彼はたくさんお金を稼ぐ。"),
    W("educate","動","教育する","Schools educate children.","学校は子どもを教育する。"),
    W("elect","動","選ぶ、選挙する","They elected a new mayor.","新しい市長を選んだ。"),
    W("encourage","動","励ます、促す","I encouraged my friend.","友達を励ました。"),
    W("entertain","動","楽しませる","The clown entertained kids.","ピエロが子どもを楽しませた。"),
    W("escape","動/名","逃げる/脱出","The bird escaped from the cage.","鳥がかごから逃げた。"),
    W("establish","動","設立する、確立する","They established a company.","会社を設立した。"),
    W("examine","動","調べる、検査する","The doctor examined me.","医者が私を診察した。"),
    W("exchange","動/名","交換する/交換","Exchange yen for dollars.","円をドルに両替して。"),
    W("exist","動","存在する","UFOs may exist.","UFOは存在するかも。"),
    W("expect","動","期待する、予期する","I expect rain today.","今日は雨だと思う。"),
    W("experience","動/名","経験する/経験","Experience new things.","新しいことを経験して。"),
    W("export","動/名","輸出する/輸出","Japan exports cars.","日本は車を輸出する。"),
    W("express","動","表現する","Express your feelings.","気持ちを表現して。"),
    W("extend","動","延長する、広げる","Extend the deadline.","締切を延長して。"),
    W("fail","動","失敗する、落第する","Don't fail the test.","試験に落ちるな。"),
    W("feed","動","食べさせる、与える","Feed the dog.","犬に餌をあげて。"),

    # Day 5: 行為・動作
    W("fight","動/名","戦う/戦い","They fought bravely.","彼らは勇敢に戦った。"),
    W("fill","動","満たす","Fill the glass with water.","コップに水を満たして。"),
    W("float","動","浮かぶ","Boats float on water.","船は水に浮かぶ。"),
    W("flow","動/名","流れる/流れ","Rivers flow to the sea.","川は海へ流れる。"),
    W("focus","動/名","集中する/焦点","Focus on your work.","仕事に集中して。"),
    W("forbid","動","禁じる","Smoking is forbidden here.","ここでの喫煙は禁止。"),
    W("force","動/名","強制する/力","Don't force me to go.","行けと強制しないで。"),
    W("forgive","動","許す","Please forgive me.","どうか許して。"),
    W("freeze","動","凍る","Water freezes at 0°C.","水は0度で凍る。"),
    W("gain","動","得る、増える","Gain experience first.","まず経験を得て。"),
    W("gather","動","集める、集まる","Gather around the fire.","火の周りに集まって。"),
    W("greet","動","挨拶する","Greet the guests.","お客さんに挨拶して。"),
    W("guess","動/名","推測する/推測","Guess what happened!","何があったか当てて！"),
    W("handle","動/名","扱う/取っ手","Handle with care.","丁寧に扱って。"),
    W("hang","動","かける、つるす","Hang your coat here.","ここにコートをかけて。"),
    W("hate","動","ひどく嫌う","I hate spiders.","クモが大嫌い。"),
    W("heal","動","治す、癒す","Time heals all wounds.","時間がすべての傷を癒す。"),
    W("hide","動","隠す、隠れる","Hide behind the tree.","木の後ろに隠れて。"),
    W("hire","動","雇う","They hired ten workers.","彼らは10人雇った。"),
    W("hit","動","打つ、当たる","He hit the ball hard.","彼はボールを強く打った。"),

    # Day 6: 思考・知覚
    W("hunt","動/名","狩る/狩り","Cats hunt mice.","猫はネズミを狩る。"),
    W("hurt","動","傷つける、痛む","My leg hurts.","足が痛い。"),
    W("identify","動","識別する、特定する","Identify the bird.","鳥を特定して。"),
    W("imagine","動","想像する","Imagine a peaceful world.","平和な世界を想像して。"),
    W("import","動/名","輸入する/輸入","We import oil.","石油を輸入する。"),
    W("improve","動","改善する、上達する","Improve your English.","英語を上達させて。"),
    W("include","動","含む","Tax is included.","税込みです。"),
    W("increase","動/名","増加する/増加","Prices increase yearly.","物価は毎年上がる。"),
    W("indicate","動","示す、指す","The arrow indicates north.","矢印は北を示す。"),
    W("influence","動/名","影響する/影響","Friends influence us.","友達は我々に影響する。"),
    W("inform","動","知らせる","Inform me of any change.","変更があれば知らせて。"),
    W("injure","動","傷つける","He injured his knee.","彼は膝を痛めた。"),
    W("insist","動","主張する、要求する","He insisted on paying.","彼は払うと言い張った。"),
    W("inspire","動","元気づける、ひらめきを与える","She inspired me.","彼女に感化された。"),
    W("install","動","取り付ける、インストール","Install the software.","ソフトを入れて。"),
    W("intend","動","〜するつもり","I intend to study abroad.","留学するつもり。"),
    W("interview","動/名","面接する/面接","I had a job interview.","就職面接があった。"),
    W("introduce","動","紹介する","Introduce yourself.","自己紹介して。"),
    W("invent","動","発明する","Edison invented the bulb.","エジソンが電球を発明した。"),
    W("invest","動","投資する","Invest in your future.","未来に投資して。"),

    # Day 7: 行動・調査
    W("investigate","動","調査する","Police investigated the crime.","警察が犯罪を調査した。"),
    W("invite","動","招待する","Invite friends over.","友達を招いて。"),
    W("involve","動","巻き込む、含む","This involves risk.","これはリスクを伴う。"),
    W("join","動","参加する、つなぐ","Join our club.","クラブに参加して。"),
    W("judge","動/名","判断する/裁判官","Don't judge by looks.","見た目で判断するな。"),
    W("kick","動/名","蹴る/蹴り","Kick the ball.","ボールを蹴って。"),
    W("kill","動","殺す","War kills many people.","戦争は多くの人を殺す。"),
    W("knock","動","ノックする、たたく","Knock before entering.","入る前にノックして。"),
    W("lay","動","置く、横たえる","Lay the book down.","本を置いて。"),
    W("lead","動/名","導く/リード","Lead the way.","案内して。"),
    W("lean","動","もたれる、傾く","Don't lean on the wall.","壁にもたれないで。"),
    W("lend","動","貸す","Lend me a pen.","ペンを貸して。"),
    W("license","動/名","認可する/免許","Driver's license.","運転免許。"),
    W("lift","動","持ち上げる","Lift the box carefully.","箱を慎重に持ち上げて。"),
    W("limit","動/名","制限する/限界","Limit your time online.","ネット時間を制限して。"),
    W("link","動/名","つなぐ/リンク","Link the two ideas.","2つの考えをつなげて。"),
    W("load","動/名","積む/荷物","Load the truck.","トラックに積んで。"),
    W("lock","動/名","鍵をかける/鍵","Lock the door.","ドアに鍵をかけて。"),
    W("manage","動","経営する、なんとか〜する","She manages a hotel.","彼女はホテルを経営する。"),
    W("mark","動/名","印をつける/印","Mark the date.","日付に印をつけて。"),

    # Day 8: 動作・状態
    W("marry","動","結婚する","They got married last year.","彼らは去年結婚した。"),
    W("measure","動/名","測る/対策","Measure the length.","長さを測って。"),
    W("melt","動","溶ける、溶かす","Ice melts in summer.","氷は夏に溶ける。"),
    W("mention","動","言及する","Don't mention it.","どういたしまして。"),
    W("mix","動","混ぜる","Mix flour and water.","小麦粉と水を混ぜて。"),
    W("multiply","動","掛ける、増える","Multiply 2 by 3.","2に3を掛けて。"),
    W("notice","動/名","気づく/通知","I noticed a smell.","においに気づいた。"),
    W("obey","動","従う","Obey the rules.","規則に従って。"),
    W("observe","動","観察する","Observe the stars.","星を観察して。"),
    W("obtain","動","手に入れる","Obtain permission first.","まず許可を得て。"),
    W("occur","動","起こる、思い浮かぶ","Accidents occur often.","事故はよく起こる。"),
    W("offer","動/名","申し出る/申し出","Offer her some tea.","彼女にお茶を勧めて。"),
    W("operate","動","操作する、手術する","Operate this machine.","この機械を操作して。"),
    W("order","動/名","注文する/順番","Order from the menu.","メニューから注文して。"),
    W("organize","動","組織する、整理する","Organize the event.","イベントを企画して。"),
    W("owe","動","借りている","I owe you ten dollars.","10ドル借りている。"),
    W("own","動/形","所有する/自分の","I own a bicycle.","自転車を持っている。"),
    W("pack","動/名","詰める/荷物","Pack your bags.","荷物を詰めて。"),
    W("paint","動/名","ペンキを塗る/絵","Paint the wall blue.","壁を青く塗って。"),
    W("participate","動","参加する","Participate in the contest.","コンテストに参加して。"),

    # Day 9: 行為・伝達
    W("pass","動","通る、合格する","I passed the exam.","試験に合格した。"),
    W("pay","動/名","支払う/給料","Pay the bill.","お会計をして。"),
    W("perform","動","演じる、行う","Perform a play.","劇を演じる。"),
    W("permit","動","許可する","Smoking is not permitted.","喫煙は許可されない。"),
    W("persuade","動","説得する","Persuade him to come.","彼が来るよう説得して。"),
    W("plant","動/名","植える/植物","Plant a tree.","木を植えて。"),
    W("point","動/名","指す/点","Point to the map.","地図を指して。"),
    W("pollute","動","汚染する","Cars pollute the air.","車は空気を汚染する。"),
    W("possess","動","所有する","She possesses talent.","彼女には才能がある。"),
    W("pour","動","注ぐ","Pour me some water.","水を注いで。"),
    W("praise","動/名","褒める/賞賛","Praise the children.","子どもを褒めて。"),
    W("predict","動","予測する","Predict the weather.","天気を予測して。"),
    W("prefer","動","好む","I prefer tea to coffee.","コーヒーより紅茶が好き。"),
    W("prepare","動","準備する","Prepare for the test.","試験の準備をして。"),
    W("present","動/名/形","贈る/プレゼント/現在の","Present a gift.","贈り物を渡して。"),
    W("preserve","動","保存する、保護する","Preserve nature.","自然を守って。"),
    W("press","動","押す、強要する","Press the button.","ボタンを押して。"),
    W("pretend","動","ふりをする","Pretend to be asleep.","寝たふりをして。"),
    W("prevent","動","防ぐ","Prevent accidents.","事故を防いで。"),
    W("produce","動/名","生産する/農産物","Japan produces cars.","日本は車を生産する。"),

    # Day 10: ビジネス・行動
    W("promote","動","昇進させる、促進する","Promote good health.","健康を促進する。"),
    W("propose","動","提案する、求婚する","He proposed to her.","彼は彼女にプロポーズした。"),
    W("protect","動","守る、保護する","Protect the environment.","環境を守って。"),
    W("prove","動","証明する","Prove your innocence.","無実を証明して。"),
    W("provide","動","提供する","We provide service.","サービスを提供する。"),
    W("publish","動","出版する","Publish a book.","本を出版する。"),
    W("pull","動","引く","Pull the door open.","ドアを引いて開けて。"),
    W("punish","動","罰する","Don't punish the child.","子どもを罰しないで。"),
    W("push","動","押す","Push the cart.","カートを押して。"),
    W("quit","動","やめる","Quit smoking.","禁煙して。"),
    W("raise","動","上げる、育てる","Raise your hand.","手を挙げて。"),
    W("reach","動","到達する、届く","Reach the top.","頂上に達して。"),
    W("realize","動","気づく、実現する","I realized my mistake.","間違いに気づいた。"),
    W("receive","動","受け取る","Receive a letter.","手紙を受け取る。"),
    W("recognize","動","認識する、認める","I recognize his voice.","彼の声がわかる。"),
    W("recommend","動","推薦する","Recommend a book.","本を推薦して。"),
    W("recover","動","回復する","Recover from illness.","病気から回復する。"),
    W("recycle","動","リサイクルする","Recycle bottles.","ビンをリサイクルして。"),
    W("reduce","動","減らす","Reduce waste.","ごみを減らして。"),
    W("refer","動","参照する、言及する","Refer to page 10.","10ページを参照して。"),

    # Day 11: 動作・関係
    W("reflect","動","反射する、反映する","Mirrors reflect light.","鏡は光を反射する。"),
    W("refuse","動","拒否する","Refuse the offer.","申し出を断って。"),
    W("regard","動/名","みなす/敬意","I regard him as a friend.","彼を友人とみなす。"),
    W("regret","動/名","後悔する/後悔","I regret nothing.","何も後悔しない。"),
    W("relate","動","関係づける","Relate the two events.","2つの出来事を関連付けて。"),
    W("relax","動","リラックスする","Relax and breathe.","リラックスして呼吸して。"),
    W("release","動","解放する、発売する","Release the bird.","鳥を放して。"),
    W("rely","動","頼る","Rely on yourself.","自分を頼って。"),
    W("remain","動","残る、〜のままでいる","Remain calm.","落ち着いていて。"),
    W("remind","動","思い出させる","Remind me later.","あとで思い出させて。"),
    W("remove","動","取り除く","Remove your shoes.","靴を脱いで。"),
    W("rent","動/名","借りる/家賃","Rent a car.","車を借りて。"),
    W("repair","動/名","修理する/修理","Repair the bike.","自転車を修理して。"),
    W("replace","動","取り替える","Replace the battery.","電池を取り替えて。"),
    W("reply","動/名","返事する/返事","Reply to the email.","メールに返信して。"),
    W("report","動/名","報告する/報告","Report the news.","ニュースを報告する。"),
    W("represent","動","代表する","She represents Japan.","彼女は日本を代表する。"),
    W("require","動","必要とする","This requires effort.","これは努力が必要。"),
    W("research","動/名","研究する/研究","Research the topic.","テーマを調査して。"),
    W("reserve","動","予約する","Reserve a table.","席を予約して。"),

    # Day 12: 行動・継続
    W("resist","動","抵抗する","Resist the temptation.","誘惑に負けないで。"),
    W("respect","動/名","尊敬する/尊敬","Respect your elders.","年上を敬って。"),
    W("respond","動","応答する","Respond quickly.","素早く返答して。"),
    W("rest","動/名","休む/休息","Rest a while.","少し休んで。"),
    W("retire","動","引退する","He retired last year.","彼は去年引退した。"),
    W("return","動","帰る、返す","Return the book.","本を返して。"),
    W("reveal","動","明かす","Reveal the truth.","真実を明かして。"),
    W("review","動/名","復習する/復習","Review the lesson.","授業を復習して。"),
    W("ride","動","乗る","Ride a bicycle.","自転車に乗って。"),
    W("rise","動","昇る、上がる","The sun rises in the east.","太陽は東から昇る。"),
    W("rob","動","盗む、奪う","They robbed the bank.","彼らは銀行を襲った。"),
    W("rule","動/名","支配する/規則","Follow the rules.","規則に従って。"),
    W("save","動","救う、節約する","Save money.","お金を貯めて。"),
    W("search","動/名","探す/捜索","Search the internet.","ネットで検索して。"),
    W("seem","動","〜のように見える","You seem tired.","疲れているようだ。"),
    W("select","動","選ぶ","Select an answer.","答えを選んで。"),
    W("sell","動","売る","Sell the old car.","古い車を売って。"),
    W("send","動","送る","Send a message.","メッセージを送って。"),
    W("separate","動/形","分ける/別々の","Separate the trash.","ごみを分別して。"),
    W("serve","動","奉仕する、給仕する","Serve the customers.","お客様にサービスを。"),

    # Day 13: 動作・状況
    W("settle","動","解決する、定住する","Settle the dispute.","争いを解決して。"),
    W("shake","動","振る、揺れる","Shake the bottle.","ビンを振って。"),
    W("share","動/名","共有する/分け前","Share with me.","分けて。"),
    W("shine","動","輝く","Stars shine at night.","星は夜輝く。"),
    W("shoot","動","撃つ、撮影する","Shoot a video.","動画を撮って。"),
    W("shout","動/名","叫ぶ/叫び","Don't shout at me.","怒鳴らないで。"),
    W("sign","動/名","署名する/印","Sign here please.","ここに署名して。"),
    W("sink","動","沈む","The boat sank.","船が沈んだ。"),
    W("solve","動","解く、解決する","Solve the problem.","問題を解いて。"),
    W("sort","動/名","分類する/種類","Sort the laundry.","洗濯物を分けて。"),
    W("spread","動","広げる、広まる","News spreads fast.","ニュースは広まるのが早い。"),
    W("stand","動","立つ、我慢する","Stand up.","立ち上がって。"),
    W("steal","動","盗む","Don't steal anything.","何も盗むな。"),
    W("stick","動/名","くっつく/棒","Stick to the plan.","計画を貫いて。"),
    W("stir","動","かき混ぜる","Stir the soup.","スープをかき混ぜて。"),
    W("strike","動","打つ、襲う","Lightning strikes trees.","雷が木を打つ。"),
    W("struggle","動/名","奮闘する/闘争","Struggle to succeed.","成功しようと奮闘する。"),
    W("succeed","動","成功する","Succeed in life.","人生で成功して。"),
    W("suffer","動","苦しむ","Suffer from a cold.","風邪で苦しむ。"),
    W("suggest","動","提案する","Suggest a place.","場所を提案して。"),

    # Day 14: 動作・支援
    W("supply","動/名","供給する/供給","Supply water.","水を供給する。"),
    W("support","動/名","支える/支援","Support your team.","チームを応援して。"),
    W("suppose","動","思う、仮定する","I suppose so.","そう思う。"),
    W("surround","動","囲む","Trees surround the house.","木が家を囲む。"),
    W("survey","動/名","調査する/調査","Survey opinions.","意見を調査する。"),
    W("survive","動","生き残る","Survive the disaster.","災害を生き残って。"),
    W("swallow","動","飲み込む","Swallow the pill.","薬を飲み込んで。"),
    W("swim","動","泳ぐ","Swim across the pool.","プールを泳いで渡る。"),
    W("swing","動","揺れる、振る","Swing the bat.","バットを振って。"),
    W("switch","動/名","切り替える/スイッチ","Switch off the lights.","電気を消して。"),
    W("tend","動","傾向がある","I tend to be late.","遅刻しがち。"),
    W("threaten","動","脅す","Don't threaten me.","脅さないで。"),
    W("throw","動","投げる","Throw the ball.","ボールを投げて。"),
    W("tie","動","結ぶ","Tie your shoes.","靴ひもを結んで。"),
    W("touch","動/名","触る/接触","Don't touch it.","触らないで。"),
    W("trade","動/名","取引する/貿易","Trade with America.","アメリカと貿易する。"),
    W("translate","動","翻訳する","Translate this sentence.","この文を訳して。"),
    W("transport","動/名","運ぶ/輸送","Transport the goods.","商品を運んで。"),
    W("trap","動/名","罠にかける/罠","Trapped in traffic.","渋滞にはまった。"),
    W("treat","動","扱う、治療する、おごる","Treat with care.","大切に扱って。"),

    # Day 15: 動作・終結
    W("trust","動/名","信用する/信頼","Trust your friends.","友達を信頼して。"),
    W("turn","動/名","回る/順番","Turn left.","左に曲がって。"),
    W("unite","動","結合する","Unite the country.","国を統一する。"),
    W("upset","動/形","動揺させる/怒った","Don't upset her.","彼女を怒らせないで。"),
    W("use","動/名","使う/使用","Use a pen.","ペンを使って。"),
    W("vary","動","変わる、変化に富む","Prices vary widely.","値段はかなり違う。"),
    W("vote","動/名","投票する/投票","Vote in the election.","選挙で投票して。"),
    W("waste","動/名","無駄にする/無駄","Don't waste food.","食べ物を無駄にしないで。"),
    W("wave","動/名","振る/波","Wave goodbye.","手を振ってさようなら。"),
    W("wear","動","身につける","Wear a coat.","コートを着て。"),
    W("weigh","動","重さを量る","Weigh yourself.","体重を量って。"),
    W("welcome","動/名","歓迎する/歓迎","Welcome home.","おかえり。"),
    W("whisper","動","ささやく","Whisper the secret.","秘密をささやいて。"),
    W("win","動","勝つ","Win the match.","試合に勝って。"),
    W("wipe","動","ふく","Wipe the table.","テーブルをふいて。"),
    W("wish","動/名","願う/願い","Wish me luck.","幸運を祈って。"),
    W("witness","動/名","目撃する/目撃者","Witness the event.","出来事を目撃する。"),
    W("wonder","動","不思議に思う","I wonder why.","なぜだろう。"),
    W("worry","動/名","心配する/心配","Don't worry.","心配しないで。"),
    W("yell","動","叫ぶ","Yell for help.","助けを求めて叫んで。"),
]


# ============================================================
# 形容詞・副詞（重要 100語） - Days 16-20
# ============================================================
ADJECTIVES = [
    # Day 16: 性質・状態1
    W("able","形","できる","I am able to swim.","泳ぐことができる。"),
    W("absolute","形","絶対の、完全な","absolute silence","完全な静寂"),
    W("abstract","形","抽象的な","abstract art","抽象芸術"),
    W("accurate","形","正確な","accurate information","正確な情報"),
    W("active","形","活発な","an active boy","活発な少年"),
    W("actual","形","実際の","actual cost","実際の費用"),
    W("afraid","形","恐れて","I'm afraid of snakes.","蛇が怖い。"),
    W("aggressive","形","攻撃的な","aggressive behavior","攻撃的な行動"),
    W("alike","形/副","似ている/同様に","The twins look alike.","双子は似ている。"),
    W("alive","形","生きている","still alive","まだ生きている"),
    W("amazing","形","驚くべき","an amazing view","素晴らしい景色"),
    W("ancient","形","古代の","ancient ruins","古代遺跡"),
    W("annoying","形","うっとうしい","an annoying sound","耳障りな音"),
    W("anxious","形","心配な、切望して","anxious about exams","試験が心配で"),
    W("apparent","形","明らかな","apparent truth","明白な真実"),
    W("appropriate","形","適切な","appropriate clothes","適切な服装"),
    W("artificial","形","人工の","artificial flowers","造花"),
    W("ashamed","形","恥じて","ashamed of myself","自分を恥じて"),
    W("asleep","形","眠って","fall asleep","眠りに落ちる"),
    W("attractive","形","魅力的な","an attractive offer","魅力的な提案"),

    # Day 17: 性質・程度
    W("available","形","利用できる","seats are available","席は空いている"),
    W("average","形/名","平均の/平均","average height","平均身長"),
    W("awake","形","目が覚めて","stay awake","起きている"),
    W("aware","形","気づいて","aware of the danger","危険に気づいて"),
    W("awful","形","ひどい","awful weather","ひどい天気"),
    W("basic","形","基本的な","basic skills","基本技能"),
    W("blind","形","目の不自由な","blind person","目の不自由な人"),
    W("bored","形","退屈した","I'm bored.","退屈だ。"),
    W("boring","形","退屈な","a boring movie","退屈な映画"),
    W("brave","形","勇敢な","a brave soldier","勇敢な兵士"),
    W("brief","形","短い、簡潔な","a brief meeting","短い会議"),
    W("brilliant","形","賢い、光輝く","a brilliant idea","素晴らしい考え"),
    W("calm","形","落ち着いた","stay calm","落ち着いて"),
    W("capable","形","能力がある","capable of swimming","泳ぐ能力がある"),
    W("careful","形","注意深い","be careful","気をつけて"),
    W("careless","形","不注意な","a careless mistake","不注意なミス"),
    W("certain","形","確かな、ある","I'm certain.","確かだ。"),
    W("cheap","形","安い","cheap food","安い食べ物"),
    W("chemical","形/名","化学の/化学物質","chemical reaction","化学反応"),
    W("civil","形","市民の、礼儀正しい","civil rights","市民権"),

    # Day 18: 性質・感情
    W("clear","形","明確な、きれいな","clear water","きれいな水"),
    W("clever","形","賢い、巧妙な","a clever boy","賢い少年"),
    W("clumsy","形","不器用な","clumsy hands","不器用な手"),
    W("comfortable","形","心地よい","comfortable bed","快適なベッド"),
    W("common","形","普通の、共通の","common sense","常識"),
    W("complete","形","完全な","complete the task","作業を完成する"),
    W("complex","形","複雑な","a complex problem","複雑な問題"),
    W("confident","形","自信がある","be confident","自信を持って"),
    W("conscious","形","意識して","conscious of danger","危険を意識して"),
    W("conservative","形","保守的な","conservative views","保守的な意見"),
    W("constant","形","絶え間ない","constant noise","絶え間ない騒音"),
    W("convenient","形","便利な","a convenient time","都合のいい時間"),
    W("correct","形/動","正しい/訂正する","correct answer","正解"),
    W("crazy","形","気が狂った、夢中","crazy about music","音楽に夢中"),
    W("creative","形","創造的な","creative work","創造的な仕事"),
    W("critical","形","批判的な、重要な","critical thinking","批判的思考"),
    W("crowded","形","混雑した","a crowded train","混んだ電車"),
    W("cruel","形","残酷な","a cruel king","残酷な王"),
    W("cultural","形","文化的な","cultural exchange","文化交流"),
    W("curious","形","好奇心の強い","curious about science","科学に興味がある"),

    # Day 19: 性質・量
    W("dangerous","形","危険な","a dangerous road","危険な道"),
    W("daily","形/副","日常の/毎日","daily routine","日課"),
    W("deaf","形","耳が不自由な","deaf people","耳の不自由な人々"),
    W("deep","形","深い","a deep lake","深い湖"),
    W("delicious","形","おいしい","delicious cake","おいしいケーキ"),
    W("dense","形","密集した、濃い","dense forest","深い森"),
    W("different","形","異なる","different colors","違う色"),
    W("difficult","形","難しい","a difficult question","難しい質問"),
    W("digital","形","デジタルの","digital camera","デジカメ"),
    W("direct","形/動","直接の/導く","direct flight","直行便"),
    W("dirty","形","汚い","dirty hands","汚れた手"),
    W("dry","形","乾いた","dry clothes","乾いた服"),
    W("eager","形","熱心な、切望して","eager to learn","学びたがって"),
    W("early","形/副","早い/早く","early morning","早朝"),
    W("eastern","形","東の","eastern Japan","東日本"),
    W("easy","形","簡単な","an easy test","簡単なテスト"),
    W("economic","形","経済の","economic growth","経済成長"),
    W("educational","形","教育的な","educational program","教育番組"),
    W("effective","形","効果的な","effective medicine","効果的な薬"),
    W("efficient","形","効率的な","efficient worker","有能な労働者"),

    # Day 20: 性質・感情2
    W("elderly","形","年配の","elderly people","年配の人々"),
    W("electric","形","電気の","electric car","電気自動車"),
    W("elementary","形","初級の、初等の","elementary school","小学校"),
    W("embarrassed","形","恥ずかしい","I was embarrassed.","恥ずかしかった。"),
    W("emotional","形","感情的な","emotional speech","感情的なスピーチ"),
    W("empty","形","空の","an empty box","空の箱"),
    W("enormous","形","巨大な","an enormous building","巨大な建物"),
    W("entire","形","全体の","the entire team","チーム全体"),
    W("environmental","形","環境の","environmental issues","環境問題"),
    W("equal","形/動","等しい/匹敵する","equal rights","平等な権利"),
    W("essential","形","必須の","essential vitamins","必須ビタミン"),
    W("ethnic","形","民族の","ethnic group","民族集団"),
    W("eventual","形","結果として起こる","eventual success","最終的な成功"),
    W("evident","形","明らかな","evident truth","明白な真実"),
    W("excellent","形","優秀な","excellent service","素晴らしいサービス"),
    W("exciting","形","わくわくする","an exciting game","興奮する試合"),
    W("exhausted","形","疲れ果てた","I'm exhausted.","くたくただ。"),
    W("expensive","形","高価な","expensive jewels","高価な宝石"),
    W("experienced","形","経験豊富な","experienced teacher","経験豊かな先生"),
    W("extra","形/副","余分な/余分に","extra time","延長時間"),
]


# ============================================================
# 名詞（テーマ別 600語） - Days 21-50
# ============================================================
NOUNS = [
    # Day 21: 自然・環境1
    W("environment","名","環境","protect the environment","環境を守る"),
    W("nature","名","自然","beautiful nature","美しい自然"),
    W("climate","名","気候","climate change","気候変動"),
    W("weather","名","天気","good weather","良い天気"),
    W("temperature","名","気温、体温","high temperature","高温"),
    W("atmosphere","名","大気、雰囲気","Earth's atmosphere","地球の大気"),
    W("pollution","名","汚染","air pollution","大気汚染"),
    W("disaster","名","災害","natural disaster","自然災害"),
    W("earthquake","名","地震","a big earthquake","大きな地震"),
    W("flood","名","洪水","heavy flood","大洪水"),
    W("hurricane","名","ハリケーン","a hurricane warning","ハリケーン警報"),
    W("typhoon","名","台風","a strong typhoon","強い台風"),
    W("storm","名","嵐","sudden storm","突然の嵐"),
    W("thunder","名","雷","loud thunder","大きな雷"),
    W("lightning","名","稲妻","sudden lightning","突然の稲妻"),
    W("drought","名","干ばつ","severe drought","深刻な干ばつ"),
    W("forest","名","森","tropical forest","熱帯林"),
    W("desert","名","砂漠","Sahara desert","サハラ砂漠"),
    W("mountain","名","山","Mount Fuji","富士山"),
    W("ocean","名","海洋","Pacific Ocean","太平洋"),

    # Day 22: 自然・環境2
    W("river","名","川","a long river","長い川"),
    W("lake","名","湖","a clear lake","澄んだ湖"),
    W("island","名","島","a small island","小さな島"),
    W("valley","名","谷","green valley","緑の谷"),
    W("coast","名","海岸","west coast","西海岸"),
    W("beach","名","浜辺","sandy beach","砂浜"),
    W("wave","名","波","big waves","大きな波"),
    W("tide","名","潮","high tide","満潮"),
    W("space","名","宇宙、空間","outer space","宇宙空間"),
    W("planet","名","惑星","planet Earth","地球"),
    W("star","名","星","shooting star","流れ星"),
    W("moon","名","月","full moon","満月"),
    W("sun","名","太陽","the sun rises","太陽が昇る"),
    W("sky","名","空","blue sky","青空"),
    W("cloud","名","雲","white cloud","白い雲"),
    W("rain","名","雨","heavy rain","大雨"),
    W("snow","名","雪","fresh snow","新雪"),
    W("ice","名","氷","melting ice","溶ける氷"),
    W("wind","名","風","strong wind","強風"),
    W("breeze","名","そよ風","cool breeze","涼しいそよ風"),

    # Day 23: 動植物
    W("animal","名","動物","wild animals","野生動物"),
    W("creature","名","生き物","sea creatures","海の生き物"),
    W("species","名","種","endangered species","絶滅危惧種"),
    W("mammal","名","哺乳類","mammals","哺乳類"),
    W("reptile","名","爬虫類","reptiles like snakes","蛇のような爬虫類"),
    W("insect","名","昆虫","insects in summer","夏の昆虫"),
    W("plant","名","植物","green plants","緑の植物"),
    W("tree","名","木","tall tree","高い木"),
    W("flower","名","花","beautiful flowers","美しい花"),
    W("grass","名","草","green grass","緑の草"),
    W("leaf","名","葉","falling leaves","落ち葉"),
    W("seed","名","種","plant seeds","種を植える"),
    W("root","名","根","tree roots","木の根"),
    W("branch","名","枝、支店","tree branches","木の枝"),
    W("fruit","名","果物","fresh fruit","新鮮な果物"),
    W("vegetable","名","野菜","fresh vegetables","新鮮な野菜"),
    W("crop","名","作物","grow crops","作物を育てる"),
    W("harvest","名","収穫","autumn harvest","秋の収穫"),
    W("agriculture","名","農業","modern agriculture","近代農業"),
    W("farming","名","農業","organic farming","有機農業"),

    # Day 24: 体・健康
    W("health","名","健康","good health","健康"),
    W("body","名","体","human body","人体"),
    W("brain","名","脳","brain power","頭脳"),
    W("heart","名","心、心臓","strong heart","強い心臓"),
    W("muscle","名","筋肉","strong muscles","強い筋肉"),
    W("bone","名","骨","broken bone","折れた骨"),
    W("skin","名","肌","soft skin","柔らかい肌"),
    W("blood","名","血","blood type","血液型"),
    W("breath","名","息","take a breath","息をする"),
    W("lung","名","肺","healthy lungs","健康な肺"),
    W("stomach","名","胃、お腹","empty stomach","空腹"),
    W("organ","名","臓器、楽器","human organs","人体の臓器"),
    W("disease","名","病気","heart disease","心臓病"),
    W("illness","名","病気","mental illness","精神疾患"),
    W("injury","名","けが、傷害","sports injury","スポーツのけが"),
    W("symptom","名","症状","flu symptoms","インフルの症状"),
    W("medicine","名","薬、医学","take medicine","薬を飲む"),
    W("drug","名","薬、麻薬","new drug","新薬"),
    W("treatment","名","治療","cancer treatment","ガン治療"),
    W("therapy","名","療法、治療","physical therapy","理学療法"),

    # Day 25: 医療・体
    W("hospital","名","病院","general hospital","総合病院"),
    W("clinic","名","診療所","dental clinic","歯科医院"),
    W("doctor","名","医者","family doctor","かかりつけ医"),
    W("nurse","名","看護師","kind nurse","親切な看護師"),
    W("patient","名/形","患者/忍耐強い","kind patient","優しい患者"),
    W("surgery","名","手術","heart surgery","心臓手術"),
    W("emergency","名","緊急事態","emergency room","救急処置室"),
    W("ambulance","名","救急車","call an ambulance","救急車を呼ぶ"),
    W("checkup","名","健康診断","yearly checkup","年1回の検査"),
    W("vaccine","名","ワクチン","new vaccine","新しいワクチン"),
    W("diet","名","食事、ダイエット","balanced diet","バランスのとれた食事"),
    W("nutrition","名","栄養","good nutrition","良い栄養"),
    W("vitamin","名","ビタミン","vitamin C","ビタミンC"),
    W("protein","名","タンパク質","high protein","高タンパク"),
    W("calorie","名","カロリー","low-calorie food","低カロリー食"),
    W("exercise","名/動","運動/運動する","daily exercise","日々の運動"),
    W("sleep","名/動","睡眠/眠る","good sleep","よく眠ること"),
    W("rest","名/動","休息/休む","need rest","休息が必要"),
    W("stress","名","ストレス","work stress","仕事のストレス"),
    W("pressure","名","圧力","blood pressure","血圧"),

    # Day 26: 教育・学習
    W("education","名","教育","higher education","高等教育"),
    W("school","名","学校","public school","公立学校"),
    W("university","名","大学","famous university","有名な大学"),
    W("college","名","大学（単科）","junior college","短期大学"),
    W("kindergarten","名","幼稚園","go to kindergarten","幼稚園に行く"),
    W("student","名","生徒","high school student","高校生"),
    W("teacher","名","先生","English teacher","英語の先生"),
    W("professor","名","教授","math professor","数学教授"),
    W("principal","名","校長","strict principal","厳しい校長"),
    W("class","名","授業、階級","math class","数学の授業"),
    W("lesson","名","授業、教訓","piano lesson","ピアノレッスン"),
    W("course","名","講座、進路","English course","英語講座"),
    W("subject","名","科目、主題","favorite subject","好きな科目"),
    W("knowledge","名","知識","wide knowledge","幅広い知識"),
    W("skill","名","技能","language skill","語学力"),
    W("ability","名","能力","reading ability","読解力"),
    W("talent","名","才能","musical talent","音楽の才能"),
    W("homework","名","宿題","do homework","宿題をする"),
    W("assignment","名","課題、宿題","write an assignment","課題を書く"),
    W("textbook","名","教科書","English textbook","英語の教科書"),

    # Day 27: 試験・成績
    W("exam","名","試験","final exam","期末試験"),
    W("examination","名","試験","entrance examination","入学試験"),
    W("test","名","テスト","math test","数学テスト"),
    W("quiz","名","小テスト","pop quiz","抜き打ちテスト"),
    W("score","名","点数、得点","high score","高得点"),
    W("grade","名","成績、学年","good grades","良い成績"),
    W("level","名","レベル、水準","high level","高いレベル"),
    W("result","名","結果","test results","テスト結果"),
    W("answer","名/動","答え/答える","correct answer","正解"),
    W("question","名","質問","good question","良い質問"),
    W("problem","名","問題","math problem","数学の問題"),
    W("solution","名","解決策、解答","find a solution","解決策を見つける"),
    W("research","名","研究","scientific research","科学研究"),
    W("study","名/動","勉強/勉強する","English study","英語の勉強"),
    W("library","名","図書館","public library","公立図書館"),
    W("dictionary","名","辞書","English dictionary","英和辞典"),
    W("notebook","名","ノート","math notebook","数学のノート"),
    W("paper","名","紙、論文","term paper","学期末論文"),
    W("essay","名","エッセイ","write an essay","エッセイを書く"),
    W("report","名","レポート","write a report","レポートを書く"),

    # Day 28: 仕事・職業
    W("job","名","仕事","good job","いい仕事"),
    W("work","名/動","仕事/働く","hard work","重労働"),
    W("career","名","経歴、職業","career change","転職"),
    W("profession","名","専門職","medical profession","医療職"),
    W("occupation","名","職業","main occupation","本業"),
    W("employee","名","従業員","new employee","新入社員"),
    W("employer","名","雇用者","good employer","良い雇い主"),
    W("boss","名","上司","strict boss","厳しい上司"),
    W("manager","名","管理者","store manager","店長"),
    W("staff","名","職員","staff member","スタッフ"),
    W("colleague","名","同僚","work colleague","職場の同僚"),
    W("worker","名","労働者","factory worker","工場労働者"),
    W("salary","名","給料","high salary","高給"),
    W("wage","名","賃金","minimum wage","最低賃金"),
    W("income","名","収入","yearly income","年収"),
    W("bonus","名","ボーナス","year-end bonus","年末ボーナス"),
    W("pension","名","年金","retirement pension","退職年金"),
    W("interview","名/動","面接/面接する","job interview","就職面接"),
    W("resume","名","履歴書","write a resume","履歴書を書く"),
    W("contract","名","契約","sign a contract","契約書に署名する"),

    # Day 29: 会社・組織
    W("company","名","会社","big company","大会社"),
    W("corporation","名","法人、企業","global corporation","世界的企業"),
    W("business","名","事業、商売","small business","小規模事業"),
    W("industry","名","産業","car industry","自動車産業"),
    W("factory","名","工場","car factory","自動車工場"),
    W("office","名","事務所","main office","本社"),
    W("branch","名","支店","branch office","支店"),
    W("department","名","部門、部","sales department","営業部"),
    W("section","名","部分、課","sports section","スポーツ欄"),
    W("project","名","計画、企画","big project","大プロジェクト"),
    W("plan","名/動","計画/計画する","make a plan","計画を立てる"),
    W("goal","名","目標","reach a goal","目標を達成する"),
    W("aim","名/動","目標/狙う","main aim","主な目的"),
    W("purpose","名","目的","clear purpose","明確な目的"),
    W("strategy","名","戦略","business strategy","事業戦略"),
    W("policy","名","方針、政策","company policy","会社の方針"),
    W("rule","名","規則","follow rules","規則を守る"),
    W("regulation","名","規制","strict regulation","厳しい規制"),
    W("agreement","名","合意、契約","reach an agreement","合意に達する"),
    W("partnership","名","提携","business partnership","業務提携"),

    # Day 30: 経済・お金
    W("economy","名","経済","global economy","世界経済"),
    W("market","名","市場","stock market","株式市場"),
    W("trade","名","貿易、取引","free trade","自由貿易"),
    W("price","名","値段","low price","低価格"),
    W("cost","名","費用","total cost","総費用"),
    W("fee","名","料金","entrance fee","入場料"),
    W("tax","名","税金","income tax","所得税"),
    W("budget","名","予算","tight budget","厳しい予算"),
    W("investment","名","投資","good investment","良い投資"),
    W("profit","名","利益","make a profit","利益を出す"),
    W("loss","名","損失","big loss","大きな損失"),
    W("debt","名","借金","heavy debt","重い借金"),
    W("loan","名","貸付、ローン","bank loan","銀行ローン"),
    W("bank","名","銀行","local bank","地元の銀行"),
    W("account","名","口座","bank account","銀行口座"),
    W("cash","名","現金","pay in cash","現金で払う"),
    W("currency","名","通貨","foreign currency","外貨"),
    W("dollar","名","ドル","US dollar","米ドル"),
    W("rate","名","率、レート","exchange rate","為替レート"),
    W("growth","名","成長","economic growth","経済成長"),

    # Day 31: 政治・社会
    W("government","名","政府","local government","地方政府"),
    W("politics","名","政治","Japanese politics","日本の政治"),
    W("policy","名","政策","economic policy","経済政策"),
    W("president","名","大統領、社長","US president","米大統領"),
    W("prime minister","名","首相","prime minister of Japan","日本の首相"),
    W("minister","名","大臣","foreign minister","外務大臣"),
    W("politician","名","政治家","famous politician","有名な政治家"),
    W("election","名","選挙","general election","総選挙"),
    W("vote","名","投票","cast a vote","投票する"),
    W("citizen","名","市民、国民","every citizen","すべての国民"),
    W("public","名/形","公衆/公の","general public","一般大衆"),
    W("nation","名","国家","modern nation","現代国家"),
    W("country","名","国","my country","私の国"),
    W("state","名","州、国家","state government","州政府"),
    W("law","名","法律","obey the law","法律を守る"),
    W("court","名","裁判所、コート","district court","地方裁判所"),
    W("justice","名","正義、司法","social justice","社会正義"),
    W("right","名","権利","human right","人権"),
    W("freedom","名","自由","freedom of speech","言論の自由"),
    W("democracy","名","民主主義","modern democracy","現代民主主義"),

    # Day 32: 国際・社会問題
    W("society","名","社会","modern society","現代社会"),
    W("community","名","地域社会","local community","地域社会"),
    W("population","名","人口","large population","大人口"),
    W("culture","名","文化","Japanese culture","日本文化"),
    W("tradition","名","伝統","old tradition","古い伝統"),
    W("custom","名","習慣、慣習","local custom","地元の習慣"),
    W("religion","名","宗教","major religion","主要宗教"),
    W("race","名","人種、競争","human race","人類"),
    W("gender","名","性別","gender equality","男女平等"),
    W("equality","名","平等","gender equality","男女平等"),
    W("discrimination","名","差別","racial discrimination","人種差別"),
    W("poverty","名","貧困","fight poverty","貧困と闘う"),
    W("crime","名","犯罪","commit a crime","罪を犯す"),
    W("criminal","名/形","犯罪者/犯罪の","catch a criminal","犯人を捕まえる"),
    W("violence","名","暴力","domestic violence","家庭内暴力"),
    W("war","名","戦争","civil war","内戦"),
    W("peace","名","平和","world peace","世界平和"),
    W("conflict","名","対立、紛争","political conflict","政治的対立"),
    W("refugee","名","難民","refugee camp","難民キャンプ"),
    W("immigrant","名","移民","new immigrant","新移民"),

    # Day 33: 家族・人間関係
    W("family","名","家族","large family","大家族"),
    W("relative","名/形","親戚/相対的","close relative","近い親戚"),
    W("parent","名","親","strict parent","厳しい親"),
    W("father","名","父","loving father","愛情深い父"),
    W("mother","名","母","kind mother","優しい母"),
    W("child","名","子供","young child","幼い子"),
    W("son","名","息子","oldest son","長男"),
    W("daughter","名","娘","youngest daughter","末娘"),
    W("brother","名","兄弟","younger brother","弟"),
    W("sister","名","姉妹","older sister","姉"),
    W("twin","名/形","双子","identical twin","一卵性双生児"),
    W("husband","名","夫","loving husband","愛情深い夫"),
    W("wife","名","妻","caring wife","気遣う妻"),
    W("couple","名","夫婦、カップル","young couple","若い夫婦"),
    W("marriage","名","結婚","happy marriage","幸せな結婚"),
    W("wedding","名","結婚式","beautiful wedding","美しい結婚式"),
    W("divorce","名","離婚","get a divorce","離婚する"),
    W("friend","名","友達","best friend","親友"),
    W("friendship","名","友情","true friendship","真の友情"),
    W("neighbor","名","隣人","kind neighbor","親切な隣人"),

    # Day 34: 食事・料理
    W("food","名","食べ物","Japanese food","日本食"),
    W("meal","名","食事","three meals","三食"),
    W("breakfast","名","朝食","big breakfast","ボリュームある朝食"),
    W("lunch","名","昼食","quick lunch","軽い昼食"),
    W("dinner","名","夕食","family dinner","家族での夕食"),
    W("snack","名","間食","afternoon snack","おやつ"),
    W("recipe","名","レシピ","secret recipe","秘伝のレシピ"),
    W("ingredient","名","材料","fresh ingredients","新鮮な材料"),
    W("flavor","名","風味","strong flavor","強い風味"),
    W("taste","名/動","味/味わう","sweet taste","甘い味"),
    W("dish","名","料理、皿","main dish","メイン料理"),
    W("kitchen","名","台所","clean kitchen","きれいな台所"),
    W("restaurant","名","レストラン","Italian restaurant","イタリアン料理店"),
    W("cafe","名","カフェ","corner cafe","角のカフェ"),
    W("menu","名","メニュー","lunch menu","昼食メニュー"),
    W("waiter","名","ウェイター","kind waiter","親切なウェイター"),
    W("chef","名","料理長","famous chef","有名シェフ"),
    W("bread","名","パン","fresh bread","焼きたてのパン"),
    W("rice","名","米、ご飯","white rice","白米"),
    W("meat","名","肉","red meat","赤身肉"),

    # Day 35: 飲食・買い物
    W("beverage","名","飲料","cold beverage","冷たい飲み物"),
    W("beverage","名","飲料","hot beverage","温かい飲み物"),
    W("alcohol","名","アルコール","no alcohol","禁酒"),
    W("dessert","名","デザート","sweet dessert","甘いデザート"),
    W("sugar","名","砂糖","less sugar","砂糖少なめ"),
    W("salt","名","塩","sea salt","海塩"),
    W("oil","名","油","olive oil","オリーブオイル"),
    W("butter","名","バター","melted butter","溶かしバター"),
    W("cheese","名","チーズ","Italian cheese","イタリアンチーズ"),
    W("egg","名","卵","fried egg","目玉焼き"),
    W("fish","名","魚","fresh fish","新鮮な魚"),
    W("chicken","名","鶏肉","grilled chicken","焼き鳥"),
    W("beef","名","牛肉","Japanese beef","和牛"),
    W("pork","名","豚肉","pork cutlet","とんかつ"),
    W("seafood","名","シーフード","fresh seafood","新鮮なシーフード"),
    W("store","名","店","grocery store","食料品店"),
    W("shop","名","店","gift shop","土産屋"),
    W("market","名","市場","fish market","魚市場"),
    W("mall","名","ショッピングモール","big mall","大きなモール"),
    W("supermarket","名","スーパー","local supermarket","地元のスーパー"),

    # Day 36: 旅行
    W("travel","名/動","旅行/旅行する","world travel","世界旅行"),
    W("trip","名","旅行","short trip","短い旅"),
    W("journey","名","旅","long journey","長い旅"),
    W("tour","名","ツアー","city tour","市内ツアー"),
    W("vacation","名","休暇","summer vacation","夏休み"),
    W("holiday","名","祝日、休日","national holiday","国民の祝日"),
    W("hotel","名","ホテル","luxury hotel","高級ホテル"),
    W("inn","名","宿","cozy inn","居心地よい宿"),
    W("reservation","名","予約","make a reservation","予約する"),
    W("ticket","名","切符","plane ticket","航空券"),
    W("passport","名","パスポート","valid passport","有効なパスポート"),
    W("visa","名","ビザ","tourist visa","観光ビザ"),
    W("baggage","名","手荷物","heavy baggage","重い荷物"),
    W("luggage","名","手荷物","carry-on luggage","機内持ち込み手荷物"),
    W("suitcase","名","スーツケース","big suitcase","大きなスーツケース"),
    W("airport","名","空港","international airport","国際空港"),
    W("station","名","駅","train station","鉄道駅"),
    W("port","名","港","busy port","にぎやかな港"),
    W("flight","名","フライト、便","direct flight","直行便"),
    W("airline","名","航空会社","Japanese airline","日本の航空会社"),

    # Day 37: 交通・移動
    W("transportation","名","交通機関","public transportation","公共交通機関"),
    W("vehicle","名","乗り物","electric vehicle","電気自動車"),
    W("car","名","車","fast car","速い車"),
    W("bus","名","バス","city bus","市バス"),
    W("train","名","電車","bullet train","新幹線"),
    W("subway","名","地下鉄","city subway","市営地下鉄"),
    W("taxi","名","タクシー","call a taxi","タクシーを呼ぶ"),
    W("bicycle","名","自転車","ride a bicycle","自転車に乗る"),
    W("motorcycle","名","オートバイ","red motorcycle","赤いバイク"),
    W("truck","名","トラック","big truck","大型トラック"),
    W("ship","名","船","cruise ship","クルーズ船"),
    W("boat","名","ボート","small boat","小舟"),
    W("airplane","名","飛行機","modern airplane","最新の飛行機"),
    W("highway","名","高速道路","busy highway","混雑した高速道路"),
    W("road","名","道","narrow road","狭い道"),
    W("street","名","通り","main street","大通り"),
    W("traffic","名","交通","heavy traffic","渋滞"),
    W("signal","名","信号","traffic signal","交通信号"),
    W("bridge","名","橋","old bridge","古い橋"),
    W("tunnel","名","トンネル","long tunnel","長いトンネル"),

    # Day 38: 場所・地理
    W("place","名","場所","favorite place","お気に入りの場所"),
    W("location","名","位置、所在地","good location","良い立地"),
    W("area","名","地域、面積","wide area","広い地域"),
    W("region","名","地方","mountain region","山岳地方"),
    W("district","名","地区","business district","ビジネス街"),
    W("city","名","市","big city","大都市"),
    W("town","名","町","small town","小さな町"),
    W("village","名","村","mountain village","山村"),
    W("capital","名","首都、資本","capital city","首都"),
    W("downtown","名","繁華街","downtown area","繁華街"),
    W("suburb","名","郊外","quiet suburb","静かな郊外"),
    W("countryside","名","田舎","peaceful countryside","平和な田舎"),
    W("center","名","中心","city center","市の中心部"),
    W("park","名","公園","national park","国立公園"),
    W("garden","名","庭","Japanese garden","日本庭園"),
    W("museum","名","博物館","art museum","美術館"),
    W("theater","名","劇場、映画館","movie theater","映画館"),
    W("stadium","名","スタジアム","sports stadium","スポーツスタジアム"),
    W("temple","名","寺","old temple","古い寺"),
    W("church","名","教会","stone church","石造りの教会"),

    # Day 39: 家・建物
    W("house","名","家","new house","新しい家"),
    W("home","名","家、家庭","sweet home","楽しい我が家"),
    W("apartment","名","マンション","small apartment","小さなアパート"),
    W("building","名","建物","tall building","高い建物"),
    W("room","名","部屋","living room","居間"),
    W("bedroom","名","寝室","quiet bedroom","静かな寝室"),
    W("bathroom","名","浴室","clean bathroom","きれいな浴室"),
    W("kitchen","名","台所","modern kitchen","近代的なキッチン"),
    W("floor","名","床、階","wooden floor","木の床"),
    W("ceiling","名","天井","high ceiling","高い天井"),
    W("wall","名","壁","white wall","白い壁"),
    W("window","名","窓","open window","開いた窓"),
    W("door","名","ドア","front door","玄関ドア"),
    W("roof","名","屋根","tiled roof","瓦屋根"),
    W("stairs","名","階段","go up stairs","階段を上る"),
    W("elevator","名","エレベーター","take the elevator","エレベーターに乗る"),
    W("furniture","名","家具","wooden furniture","木の家具"),
    W("table","名","テーブル","round table","丸テーブル"),
    W("chair","名","椅子","wooden chair","木の椅子"),
    W("bed","名","ベッド","comfortable bed","快適なベッド"),

    # Day 40: 物・道具
    W("tool","名","道具","useful tool","便利な道具"),
    W("equipment","名","設備、装備","sports equipment","スポーツ用具"),
    W("device","名","装置","new device","新しい装置"),
    W("machine","名","機械","washing machine","洗濯機"),
    W("computer","名","コンピューター","personal computer","パソコン"),
    W("laptop","名","ノートPC","new laptop","新しいノートPC"),
    W("smartphone","名","スマホ","latest smartphone","最新のスマホ"),
    W("tablet","名","タブレット","new tablet","新しいタブレット"),
    W("printer","名","プリンター","color printer","カラープリンター"),
    W("camera","名","カメラ","digital camera","デジカメ"),
    W("phone","名","電話","old phone","古い電話"),
    W("television","名","テレビ","large television","大きなテレビ"),
    W("radio","名","ラジオ","car radio","カーラジオ"),
    W("clock","名","時計","wall clock","壁掛け時計"),
    W("watch","名/動","腕時計/見る","wrist watch","腕時計"),
    W("battery","名","電池","new battery","新しい電池"),
    W("charger","名","充電器","phone charger","スマホ充電器"),
    W("cable","名","ケーブル、線","USB cable","USBケーブル"),
    W("button","名","ボタン","red button","赤いボタン"),
    W("screen","名","画面","big screen","大画面"),

    # Day 41: 科学・技術
    W("science","名","科学","modern science","現代科学"),
    W("technology","名","技術","high technology","ハイテク"),
    W("engineering","名","工学","civil engineering","土木工学"),
    W("invention","名","発明","great invention","大発明"),
    W("discovery","名","発見","scientific discovery","科学的発見"),
    W("experiment","名","実験","science experiment","科学実験"),
    W("theory","名","理論","scientific theory","科学理論"),
    W("data","名","データ、資料","collect data","データを集める"),
    W("information","名","情報","useful information","役立つ情報"),
    W("internet","名","インターネット","fast internet","速いネット"),
    W("website","名","ウェブサイト","useful website","役立つサイト"),
    W("email","名","メール","send an email","メールを送る"),
    W("message","名","メッセージ","short message","短いメッセージ"),
    W("software","名","ソフト","new software","新ソフト"),
    W("application","名","アプリ、申請","mobile application","モバイルアプリ"),
    W("system","名","システム、制度","computer system","コンピュータ・システム"),
    W("network","名","ネットワーク","social network","SNS"),
    W("signal","名","信号","weak signal","弱い信号"),
    W("password","名","パスワード","secret password","秘密のパスワード"),
    W("file","名","ファイル","important file","重要なファイル"),

    # Day 42: 物質・科学
    W("matter","名","物質、問題","important matter","重要な事柄"),
    W("material","名","材料","building material","建築資材"),
    W("metal","名","金属","heavy metal","重金属"),
    W("plastic","名","プラスチック","plastic bag","ビニール袋"),
    W("wood","名","木材","oak wood","オーク材"),
    W("paper","名","紙","white paper","白い紙"),
    W("rubber","名","ゴム","rubber band","ゴムバンド"),
    W("glass","名","ガラス、コップ","broken glass","割れたガラス"),
    W("steel","名","鋼鉄","strong steel","強い鋼鉄"),
    W("iron","名","鉄","iron bar","鉄の棒"),
    W("gold","名","金","pure gold","純金"),
    W("silver","名","銀","silver ring","銀の指輪"),
    W("copper","名","銅","copper wire","銅線"),
    W("oxygen","名","酸素","need oxygen","酸素が必要"),
    W("hydrogen","名","水素","hydrogen gas","水素ガス"),
    W("carbon","名","炭素","carbon dioxide","二酸化炭素"),
    W("electricity","名","電気","save electricity","節電する"),
    W("energy","名","エネルギー","solar energy","太陽エネルギー"),
    W("gas","名","ガス、気体","natural gas","天然ガス"),
    W("liquid","名","液体","clear liquid","透明な液体"),

    # Day 43: 動物
    W("dog","名","犬","cute dog","かわいい犬"),
    W("cat","名","猫","black cat","黒猫"),
    W("bird","名","鳥","small bird","小鳥"),
    W("fish","名","魚","goldfish","金魚"),
    W("horse","名","馬","fast horse","速い馬"),
    W("cow","名","牛","dairy cow","乳牛"),
    W("pig","名","豚","pink pig","ピンクの豚"),
    W("sheep","名","羊","white sheep","白い羊"),
    W("rabbit","名","ウサギ","cute rabbit","かわいいウサギ"),
    W("mouse","名","ネズミ","tiny mouse","小さなネズミ"),
    W("elephant","名","象","huge elephant","巨大な象"),
    W("lion","名","ライオン","brave lion","勇敢なライオン"),
    W("tiger","名","虎","wild tiger","野生の虎"),
    W("bear","名","熊","brown bear","茶色の熊"),
    W("monkey","名","猿","clever monkey","賢い猿"),
    W("wolf","名","狼","gray wolf","灰色狼"),
    W("fox","名","キツネ","red fox","赤キツネ"),
    W("deer","名","鹿","wild deer","野生の鹿"),
    W("snake","名","ヘビ","green snake","緑のヘビ"),
    W("dolphin","名","イルカ","clever dolphin","賢いイルカ"),

    # Day 44: スポーツ
    W("sport","名","スポーツ","winter sport","冬のスポーツ"),
    W("game","名","ゲーム、試合","baseball game","野球の試合"),
    W("team","名","チーム","strong team","強いチーム"),
    W("player","名","選手","baseball player","野球選手"),
    W("coach","名","コーチ","strict coach","厳しいコーチ"),
    W("captain","名","キャプテン","team captain","チームキャプテン"),
    W("match","名","試合","tennis match","テニスの試合"),
    W("tournament","名","トーナメント","golf tournament","ゴルフ大会"),
    W("championship","名","選手権","world championship","世界選手権"),
    W("competition","名","競争","tough competition","厳しい競争"),
    W("victory","名","勝利","sweet victory","甘い勝利"),
    W("defeat","名","敗北","crushing defeat","壊滅的敗北"),
    W("medal","名","メダル","gold medal","金メダル"),
    W("trophy","名","トロフィー","big trophy","大きなトロフィー"),
    W("prize","名","賞","first prize","一等賞"),
    W("award","名","賞","Nobel award","ノーベル賞"),
    W("baseball","名","野球","play baseball","野球をする"),
    W("soccer","名","サッカー","watch soccer","サッカーを見る"),
    W("tennis","名","テニス","play tennis","テニスをする"),
    W("basketball","名","バスケ","love basketball","バスケが好き"),

    # Day 45: 芸術・娯楽
    W("art","名","芸術","modern art","近代美術"),
    W("music","名","音楽","classical music","クラシック音楽"),
    W("song","名","歌","popular song","人気の歌"),
    W("dance","名/動","ダンス/踊る","traditional dance","伝統舞踊"),
    W("movie","名","映画","action movie","アクション映画"),
    W("film","名","映画","old film","昔の映画"),
    W("drama","名","ドラマ","TV drama","テレビドラマ"),
    W("comedy","名","コメディ","funny comedy","面白いコメディ"),
    W("concert","名","コンサート","rock concert","ロックコンサート"),
    W("performance","名","演技、公演","great performance","素晴らしい演技"),
    W("show","名","ショー、番組","talk show","トーク番組"),
    W("event","名","行事","big event","大きな行事"),
    W("festival","名","祭り","summer festival","夏祭り"),
    W("ceremony","名","式典","opening ceremony","開会式"),
    W("party","名","パーティー","birthday party","誕生パーティー"),
    W("artist","名","芸術家","famous artist","有名芸術家"),
    W("painter","名","画家","oil painter","油絵画家"),
    W("musician","名","音楽家","jazz musician","ジャズミュージシャン"),
    W("singer","名","歌手","pop singer","ポップ歌手"),
    W("actor","名","俳優","Hollywood actor","ハリウッド俳優"),

    # Day 46: 本・メディア
    W("book","名","本","reading book","読書"),
    W("novel","名","小説","mystery novel","推理小説"),
    W("story","名","物語","short story","短編"),
    W("poem","名","詩","love poem","恋愛詩"),
    W("magazine","名","雑誌","fashion magazine","ファッション誌"),
    W("newspaper","名","新聞","morning newspaper","朝刊"),
    W("article","名","記事、品物","news article","ニュース記事"),
    W("author","名","著者","best-selling author","ベストセラー作家"),
    W("writer","名","作家","famous writer","有名作家"),
    W("editor","名","編集者","chief editor","編集長"),
    W("media","名","メディア","social media","ソーシャルメディア"),
    W("news","名","ニュース","breaking news","速報"),
    W("channel","名","チャンネル","TV channel","TVチャンネル"),
    W("program","名","番組、プログラム","TV program","テレビ番組"),
    W("series","名","シリーズ、連続","TV series","TVシリーズ"),
    W("character","名","登場人物、性格","main character","主人公"),
    W("hero","名","英雄","national hero","国民的英雄"),
    W("plot","名","筋、陰謀","story plot","物語の筋"),
    W("scene","名","場面","love scene","愛のシーン"),
    W("script","名","脚本","movie script","映画の脚本"),

    # Day 47: 時間
    W("time","名","時間","short time","短い時間"),
    W("moment","名","瞬間","perfect moment","完璧な瞬間"),
    W("minute","名","分","every minute","毎分"),
    W("hour","名","時間","one hour","1時間"),
    W("day","名","日","sunny day","晴れた日"),
    W("week","名","週","this week","今週"),
    W("month","名","月","next month","来月"),
    W("year","名","年","new year","新年"),
    W("decade","名","10年","past decade","過去10年"),
    W("century","名","世紀","21st century","21世紀"),
    W("future","名/形","未来/将来の","bright future","明るい未来"),
    W("present","名/形","現在/現在の","at present","現在"),
    W("past","名/形","過去/過去の","in the past","過去に"),
    W("season","名","季節","four seasons","四季"),
    W("spring","名","春","early spring","早春"),
    W("summer","名","夏","hot summer","暑い夏"),
    W("autumn","名","秋","cool autumn","涼しい秋"),
    W("winter","名","冬","cold winter","寒い冬"),
    W("weekend","名","週末","busy weekend","忙しい週末"),
    W("weekday","名","平日","weekdays only","平日のみ"),

    # Day 48: 抽象概念1
    W("idea","名","考え","good idea","良い考え"),
    W("opinion","名","意見","different opinion","違う意見"),
    W("view","名","見方、景色","beautiful view","美しい眺め"),
    W("thought","名","考え","deep thought","深い思考"),
    W("mind","名","心、精神","strong mind","強い精神"),
    W("memory","名","記憶","good memory","良い記憶力"),
    W("dream","名","夢","sweet dream","良い夢"),
    W("hope","名","希望","new hope","新たな希望"),
    W("wish","名","願い","make a wish","願い事をする"),
    W("desire","名","欲求","strong desire","強い欲望"),
    W("interest","名","興味","great interest","強い関心"),
    W("attention","名","注意","pay attention","注意を払う"),
    W("concern","名","心配","main concern","主な心配"),
    W("worry","名","心配","big worry","大きな心配"),
    W("fear","名","恐怖","fear of heights","高所恐怖"),
    W("anger","名","怒り","strong anger","強い怒り"),
    W("joy","名","喜び","great joy","大きな喜び"),
    W("sadness","名","悲しみ","deep sadness","深い悲しみ"),
    W("surprise","名","驚き","big surprise","大きな驚き"),
    W("pride","名","誇り","national pride","国民の誇り"),

    # Day 49: 抽象概念2
    W("life","名","人生、生命","happy life","幸せな人生"),
    W("death","名","死","sudden death","突然の死"),
    W("birth","名","誕生","date of birth","誕生日"),
    W("age","名","年齢","old age","老齢"),
    W("youth","名","若さ、青春","carefree youth","気楽な青春"),
    W("childhood","名","子供時代","happy childhood","幸せな子供時代"),
    W("experience","名","経験","work experience","職務経験"),
    W("event","名","出来事","big event","大事件"),
    W("situation","名","状況","difficult situation","難しい状況"),
    W("condition","名","状態、条件","good condition","良い状態"),
    W("circumstance","名","状況","under any circumstance","どんな状況でも"),
    W("fact","名","事実","real fact","本当の事実"),
    W("truth","名","真実","tell the truth","真実を語る"),
    W("reality","名","現実","harsh reality","厳しい現実"),
    W("reason","名","理由","good reason","良い理由"),
    W("cause","名","原因","main cause","主な原因"),
    W("effect","名","結果、効果","side effect","副作用"),
    W("result","名","結果","final result","最終結果"),
    W("consequence","名","結果","serious consequence","深刻な結果"),
    W("influence","名","影響","positive influence","良い影響"),

    # Day 50: 抽象概念3
    W("change","名","変化","big change","大きな変化"),
    W("progress","名","進歩","steady progress","着実な進歩"),
    W("development","名","発展","economic development","経済発展"),
    W("success","名","成功","great success","大成功"),
    W("failure","名","失敗","total failure","完全な失敗"),
    W("achievement","名","達成","great achievement","大きな達成"),
    W("attempt","名","試み","first attempt","初めての試み"),
    W("effort","名","努力","great effort","大きな努力"),
    W("challenge","名","挑戦","big challenge","大きな挑戦"),
    W("opportunity","名","機会","good opportunity","良い機会"),
    W("chance","名","機会、可能性","last chance","最後の機会"),
    W("possibility","名","可能性","real possibility","現実的な可能性"),
    W("choice","名","選択","tough choice","難しい選択"),
    W("decision","名","決定","important decision","重要な決定"),
    W("option","名","選択肢","best option","最良の選択"),
    W("advantage","名","利点","big advantage","大きな利点"),
    W("disadvantage","名","欠点","main disadvantage","主な欠点"),
    W("benefit","名","利益、恩恵","health benefit","健康への恩恵"),
    W("value","名","価値","real value","本当の価値"),
    W("importance","名","重要性","great importance","大いなる重要性"),
]


# ============================================================
# 上級動詞（300語） - Days 51-65
# ============================================================
ADVANCED_VERBS = [
    # Day 51: 抽象動作1
    W("abandon","動","捨てる、見捨てる","abandon a plan","計画を放棄する"),
    W("absorb","動","吸収する","absorb water","水を吸収する"),
    W("accelerate","動","加速する","accelerate growth","成長を加速する"),
    W("accompany","動","同伴する","accompany a child","子供に付き添う"),
    W("accomplish","動","成し遂げる","accomplish a goal","目標を達成する"),
    W("accuse","動","非難する、告発する","accuse him of theft","彼を窃盗で告発する"),
    W("acknowledge","動","認める","acknowledge the truth","真実を認める"),
    W("adapt","動","適応する","adapt to change","変化に適応する"),
    W("address","動/名","対処する、演説する/住所","address the issue","問題に対処する"),
    W("adjust","動","調整する","adjust the volume","音量を調整する"),
    W("administer","動","管理する、投与する","administer a test","試験を実施する"),
    W("admire","動","賞賛する","admire her courage","彼女の勇気を称える"),
    W("advise","動","助言する","advise patience","忍耐を勧める"),
    W("alarm","動/名","警告する/警報","alarm clock","目覚まし時計"),
    W("alert","動/形","警報を出す/警戒した","alert the police","警察に通報する"),
    W("allow","動","許す","allow smoking","喫煙を許可する"),
    W("alter","動","変える","alter the design","デザインを変える"),
    W("amuse","動","楽しませる","amuse children","子供を楽しませる"),
    W("analyze","動","分析する","analyze the data","データを分析する"),
    W("anticipate","動","予期する","anticipate problems","問題を予期する"),

    # Day 52: 抽象動作2
    W("appeal","動/名","訴える/魅力","appeal to emotion","感情に訴える"),
    W("appear","動","現れる、〜に見える","suddenly appear","突然現れる"),
    W("appoint","動","任命する","appoint a leader","リーダーを任命する"),
    W("appreciate","動","感謝する、評価する","appreciate your help","助けに感謝する"),
    W("approve","動","承認する","approve the plan","計画を承認する"),
    W("arise","動","生じる","problems arise","問題が生じる"),
    W("arrest","動","逮捕する","arrest the thief","泥棒を逮捕する"),
    W("assemble","動","集める、組み立てる","assemble the parts","部品を組み立てる"),
    W("assert","動","主張する","assert one's right","権利を主張する"),
    W("assess","動","評価する","assess the damage","損害を評価する"),
    W("assign","動","割り当てる","assign homework","宿題を出す"),
    W("assist","動","援助する","assist the elderly","お年寄りを助ける"),
    W("associate","動","関連付ける","associate with friends","友達と付き合う"),
    W("attach","動","付ける、添付する","attach a file","ファイルを添付する"),
    W("attack","動/名","攻撃する/攻撃","attack the enemy","敵を攻撃する"),
    W("attend","動","出席する","attend a meeting","会議に出席する"),
    W("attribute","動/名","〜に帰する/属性","attribute success to luck","成功を運のおかげにする"),
    W("authorize","動","権限を与える","authorize a payment","支払いを承認する"),
    W("award","動/名","授与する/賞","award a medal","メダルを授与する"),
    W("balance","動/名","釣り合いをとる/均衡","balance the budget","予算の均衡を取る"),

    # Day 53: 抽象動作3
    W("ban","動/名","禁止する/禁止","ban smoking","喫煙を禁止する"),
    W("bear","動","耐える、産む","bear pain","痛みに耐える"),
    W("beat","動","打ち負かす、打つ","beat the rival","ライバルを倒す"),
    W("beg","動","懇願する","beg for help","助けを請う"),
    W("benefit","動/名","利益を得る/利益","benefit from training","訓練の恩恵を受ける"),
    W("bet","動/名","賭ける/賭け","bet on a horse","馬に賭ける"),
    W("bid","動/名","入札する/入札","bid for a contract","契約に入札する"),
    W("bind","動","縛る","bind the books","本を綴じる"),
    W("bite","動/名","噛む/かみつき","dog bites","犬が噛む"),
    W("blow","動","吹く","wind blows","風が吹く"),
    W("boast","動","自慢する","boast of success","成功を自慢する"),
    W("boost","動","押し上げる、増やす","boost sales","売上を伸ばす"),
    W("bother","動","悩ます、邪魔する","Don't bother me.","邪魔しないで。"),
    W("bow","動/名","お辞儀する/弓","bow politely","丁寧にお辞儀する"),
    W("brake","動/名","ブレーキをかける/ブレーキ","brake suddenly","急ブレーキをかける"),
    W("breed","動/名","繁殖する/種類","breed cattle","牛を飼育する"),
    W("broadcast","動/名","放送する/放送","broadcast live","生放送する"),
    W("calculate","動","計算する","calculate the total","合計を計算する"),
    W("campaign","動/名","運動する/運動","campaign for election","選挙運動をする"),
    W("cancel","動","取り消す","cancel a flight","フライトをキャンセルする"),

    # Day 54: 抽象動作4
    W("cast","動/名","投げる/配役","cast a vote","投票する"),
    W("cease","動","やめる、終わる","cease fire","発砲をやめる"),
    W("characterize","動","特徴づける","characterize the era","時代を特徴づける"),
    W("charge","動/名","請求する、充電する/料金","charge a fee","料金を請求する"),
    W("cheat","動/名","だます/詐欺","cheat on exam","試験でカンニングする"),
    W("check","動/名","確認する/小切手","check the time","時間を確認する"),
    W("cheer","動/名","声援する/歓声","cheer the team","チームを応援する"),
    W("chew","動","噛む","chew slowly","ゆっくり噛む"),
    W("circulate","動","循環する、流通する","blood circulates","血液が循環する"),
    W("cite","動","引用する","cite a source","出典を引用する"),
    W("claim","動/名","主張する/主張","claim damages","損害を請求する"),
    W("clarify","動","明確にする","clarify the rule","規則を明確にする"),
    W("classify","動","分類する","classify books","本を分類する"),
    W("clean","動/形","掃除する/きれいな","clean the room","部屋を掃除する"),
    W("climb","動","登る","climb a mountain","山を登る"),
    W("clip","動/名","切り取る/留め金","clip an article","記事を切り抜く"),
    W("coach","動/名","指導する/コーチ","coach the team","チームを指導する"),
    W("coincide","動","一致する","coincide with my view","私の見解と一致する"),
    W("collaborate","動","協力する","collaborate on a project","プロジェクトで協力する"),
    W("collapse","動/名","崩壊する/崩壊","building collapse","建物の崩壊"),

    # Day 55: 抽象動作5
    W("combine","動","結合する","combine ideas","アイデアを結合する"),
    W("commence","動","始める","commence operations","操業を開始する"),
    W("comment","動/名","コメントする/コメント","comment on news","ニュースにコメントする"),
    W("commit","動","委ねる、約束する","commit a crime","罪を犯す"),
    W("compete","動","競争する","compete in sports","スポーツで競う"),
    W("compose","動","構成する、作曲する","compose a song","曲を作る"),
    W("comprehend","動","理解する","comprehend the topic","話題を理解する"),
    W("compress","動","圧縮する","compress a file","ファイルを圧縮する"),
    W("concentrate","動","集中する","concentrate on study","勉強に集中する"),
    W("conduct","動/名","行う、指揮する/行為","conduct research","研究を行う"),
    W("confess","动","告白する","confess a sin","罪を告白する"),
    W("confine","动","制限する、閉じ込める","confine a dog","犬を閉じ込める"),
    W("confront","動","直面する","confront difficulty","困難に立ち向かう"),
    W("confuse","動","混乱させる","confuse the audience","聴衆を混乱させる"),
    W("congratulate","動","祝う","congratulate the winner","勝者を祝う"),
    W("conquer","動","征服する","conquer a country","国を征服する"),
    W("consent","動/名","同意する/同意","consent to marriage","結婚に同意する"),
    W("conserve","動","保護する、節約する","conserve energy","エネルギーを節約する"),
    W("constitute","動","構成する","constitute a team","チームを構成する"),
    W("construct","動","建設する","construct a bridge","橋を建設する"),

    # Day 56: 抽象動作6
    W("consult","動","相談する","consult a doctor","医者に相談する"),
    W("contact","動/名","接触する/連絡","contact me later","あとで連絡して"),
    W("contradict","動","矛盾する","contradict the story","話と矛盾する"),
    W("convert","動","変換する","convert yen to dollars","円をドルに変換する"),
    W("convey","動","伝える","convey a message","メッセージを伝える"),
    W("cooperate","動","協力する","cooperate with friends","友達と協力する"),
    W("cope","動","対処する","cope with stress","ストレスに対処する"),
    W("correct","動/形","訂正する/正しい","correct mistakes","間違いを訂正する"),
    W("correspond","動","対応する、文通する","correspond to needs","ニーズに合う"),
    W("count","動","数える","count to ten","10まで数える"),
    W("cover","動/名","覆う/カバー","cover the table","テーブルを覆う"),
    W("crack","動/名","ひびを入れる/ひび","crack the code","暗号を解く"),
    W("cram","動","詰め込む","cram for exams","試験のために詰め込む"),
    W("crash","動/名","衝突する/衝突","car crash","自動車事故"),
    W("crawl","動","這う","babies crawl","赤ちゃんが這う"),
    W("criticize","動","批判する","criticize the plan","計画を批判する"),
    W("cross","動/形","横切る/不機嫌な","cross the street","通りを渡る"),
    W("crush","動","押しつぶす","crush the can","缶を潰す"),
    W("cry","動/名","泣く/叫び","babies cry","赤ちゃんが泣く"),
    W("cure","動/名","治す/治療法","cure a disease","病気を治す"),

    # Day 57: 抽象動作7
    W("dare","動","あえて〜する","dare to dream","夢を見る勇気を持つ"),
    W("date","動/名","デートする/日付","date for years","何年も付き合う"),
    W("decline","動/名","断る、衰退する/低下","decline an offer","申し出を断る"),
    W("decorate","動","飾る","decorate the tree","木を飾る"),
    W("dedicate","動","捧げる","dedicate his life","人生を捧げる"),
    W("deduct","動","差し引く","deduct from salary","給料から差し引く"),
    W("define","動","定義する","define a word","単語を定義する"),
    W("delete","動","削除する","delete a file","ファイルを削除する"),
    W("deliver","動","配達する","deliver a speech","演説をする"),
    W("demonstrate","動","証明する、実演する","demonstrate skill","技能を実演する"),
    W("depart","動","出発する","depart at noon","正午に出発する"),
    W("depress","動","落ち込ませる","feel depressed","落ち込む"),
    W("deprive","動","奪う","deprive of rights","権利を奪う"),
    W("derive","動","由来する、引き出す","derive from Latin","ラテン語から派生する"),
    W("descend","動","降りる","descend the stairs","階段を降りる"),
    W("design","動/名","設計する/デザイン","design a house","家を設計する"),
    W("detect","動","発見する、検出する","detect a fault","欠陥を発見する"),
    W("detain","動","拘留する","detain a suspect","容疑者を拘束する"),
    W("determine","動","決定する","determine the cause","原因を特定する"),
    W("devote","動","捧げる","devote time to family","家族に時間を捧げる"),

    # Day 58: 抽象動作8
    W("diagnose","動","診断する","diagnose a disease","病気を診断する"),
    W("differ","動","異なる","opinions differ","意見が異なる"),
    W("dig","動","掘る","dig a hole","穴を掘る"),
    W("dim","動/形","薄暗くする/薄暗い","dim the light","明かりを暗くする"),
    W("direct","動/形","指揮する/直接の","direct a movie","映画を監督する"),
    W("disagree","動","意見が違う","disagree with him","彼に同意しない"),
    W("disappoint","動","失望させる","feel disappointed","がっかりする"),
    W("disapprove","動","認めない","disapprove the plan","計画を承認しない"),
    W("discharge","動/名","排出する/排出","discharge water","水を放出する"),
    W("disclose","動","暴露する","disclose information","情報を開示する"),
    W("disconnect","動","切断する","disconnect the call","電話を切る"),
    W("discount","動/名","割引する/割引","discount price","割引価格"),
    W("disgust","動/名","嫌悪させる/嫌悪","feel disgusted","嫌悪を感じる"),
    W("dismiss","動","解雇する、退ける","dismiss a worker","労働者を解雇する"),
    W("display","動/名","展示する/展示","display art","芸術を展示する"),
    W("dispose","動","処分する","dispose of trash","ゴミを処分する"),
    W("distinguish","動","区別する","distinguish good and evil","善悪を区別する"),
    W("distract","動","気をそらす","distract a child","子供の気をそらす"),
    W("distribute","動","配布する","distribute flyers","チラシを配布する"),
    W("disturb","動","じゃまする","Don't disturb me.","邪魔しないで。"),

    # Day 59: 抽象動作9
    W("dive","動","飛び込む","dive into the pool","プールに飛び込む"),
    W("divorce","動/名","離婚する/離婚","get divorced","離婚する"),
    W("donate","動","寄付する","donate money","お金を寄付する"),
    W("doubt","動/名","疑う/疑い","doubt his story","彼の話を疑う"),
    W("download","動/名","ダウンロードする","download a file","ファイルをDLする"),
    W("dozen","名","ダース","a dozen eggs","卵1ダース"),
    W("draft","動/名","下書きする/下書き","draft a letter","手紙の下書きをする"),
    W("drain","動/名","排水する/排水管","drain the pool","プールから水を抜く"),
    W("draw","動","引く、描く","draw a picture","絵を描く"),
    W("dread","動","恐れる","dread tomorrow","明日を恐れる"),
    W("dress","動/名","服を着る/ドレス","dress up","おしゃれする"),
    W("drift","動/名","漂う/漂流","clouds drift","雲が流れる"),
    W("drill","動/名","訓練する/ドリル","drill the soldiers","兵士を訓練する"),
    W("drown","動","溺れる","drown in the river","川で溺れる"),
    W("drum","動/名","ドラムを叩く/太鼓","drum a beat","リズムを叩く"),
    W("dump","動/名","捨てる/ゴミ捨て場","dump waste","ごみを捨てる"),
    W("duplicate","動/名","複製する/複製","duplicate keys","合鍵を作る"),
    W("dwell","動","住む、こだわる","dwell on the past","過去にこだわる"),
    W("ease","動/名","和らげる/容易さ","ease the pain","痛みを和らげる"),
    W("eat","動","食べる","eat dinner","夕食を食べる"),

    # Day 60: 抽象動作10
    W("elaborate","動/形","詳述する/手の込んだ","elaborate on the plan","計画を詳述する"),
    W("eliminate","動","除去する","eliminate waste","無駄をなくす"),
    W("embrace","動","抱きしめる、受け入れる","embrace change","変化を受け入れる"),
    W("emerge","動","現れる","emerge from water","水中から現れる"),
    W("emit","動","放出する","emit smoke","煙を出す"),
    W("emphasize","動","強調する","emphasize safety","安全を強調する"),
    W("employ","動","雇う、用いる","employ workers","労働者を雇う"),
    W("enable","動","可能にする","enable students to learn","学生が学べるようにする"),
    W("enclose","動","囲む、同封する","enclose a check","小切手を同封する"),
    W("encounter","動/名","遭遇する/遭遇","encounter a problem","問題に遭遇する"),
    W("end","動/名","終わる/終わり","end a meeting","会議を終える"),
    W("endure","動","耐える","endure hardship","苦難に耐える"),
    W("enforce","動","施行する","enforce the law","法を執行する"),
    W("engage","動","従事する、婚約する","engage in study","勉強に従事する"),
    W("enhance","動","高める","enhance flavor","風味を高める"),
    W("enlarge","動","拡大する","enlarge a photo","写真を拡大する"),
    W("enroll","動","登録する","enroll in school","学校に入学する"),
    W("ensure","動","確実にする","ensure safety","安全を確保する"),
    W("enter","動","入る","enter the room","部屋に入る"),
    W("entitle","動","資格を与える","entitle to vote","投票権を与える"),

    # Day 61: 抽象動作11
    W("entrust","動","委ねる","entrust a task","仕事を任せる"),
    W("envy","動/名","羨む/嫉妬","envy her success","彼女の成功を羨む"),
    W("equip","動","装備する","equip the team","チームを装備する"),
    W("erase","動","消す","erase the board","黒板を消す"),
    W("erupt","動","噴火する","volcano erupts","火山が噴火する"),
    W("evaluate","動","評価する","evaluate performance","業績を評価する"),
    W("evolve","動","進化する","species evolve","種が進化する"),
    W("exceed","動","超える","exceed the limit","限度を超える"),
    W("excel","動","秀でる","excel in math","数学に秀でる"),
    W("exchange","動/名","交換する/交換","exchange ideas","アイデアを交換する"),
    W("exclude","動","除外する","exclude from team","チームから除外する"),
    W("execute","動","実行する","execute a plan","計画を実行する"),
    W("exhibit","動/名","展示する/展覧会","exhibit paintings","絵画を展示する"),
    W("expand","動","拡大する","expand business","事業を拡大する"),
    W("explode","動","爆発する","bombs explode","爆弾が爆発する"),
    W("explore","動","探検する","explore the cave","洞窟を探検する"),
    W("expose","動","さらす","expose to sun","太陽にさらす"),
    W("extinguish","動","消す","extinguish a fire","火を消す"),
    W("extract","動","抜き取る","extract a tooth","歯を抜く"),
    W("face","動/名","直面する/顔","face problems","問題に直面する"),

    # Day 62: 抽象動作12
    W("facilitate","動","容易にする","facilitate communication","コミュニケーションを促進する"),
    W("fade","動","薄れる","colors fade","色があせる"),
    W("favor","動/名","好む/好意","favor blue","青を好む"),
    W("fear","動/名","恐れる/恐怖","fear the dark","暗闇を恐れる"),
    W("feature","動/名","特徴とする/特徴","feature an artist","アーティストを特集する"),
    W("feel","動","感じる","feel cold","寒く感じる"),
    W("fetch","動","取ってくる","fetch the ball","ボールを取ってくる"),
    W("figure","動/名","計算する/数字","figure out","解決する"),
    W("file","動/名","ファイルする/ファイル","file a complaint","苦情を申し立てる"),
    W("find","動","見つける","find a key","鍵を見つける"),
    W("finance","動/名","資金提供する/財政","finance a project","プロジェクトに資金提供する"),
    W("fire","動/名","解雇する、発砲する/火","fire a worker","労働者を解雇する"),
    W("fit","動/形","合う/健康な","clothes fit","服が合う"),
    W("fix","動","修理する","fix the car","車を修理する"),
    W("flee","動","逃げる","flee danger","危険から逃げる"),
    W("flip","動","ひっくり返す","flip a coin","コインを投げる"),
    W("flood","動/名","氾濫する/洪水","flood the basement","地下室が浸水する"),
    W("flourish","動","繁栄する","business flourishes","ビジネスが繁栄する"),
    W("fly","動","飛ぶ","birds fly","鳥が飛ぶ"),
    W("fold","動","折る","fold the paper","紙を折る"),

    # Day 63: 抽象動作13
    W("forge","動","偽造する、鍛造する","forge a signature","署名を偽造する"),
    W("forgive","動","許す","forgive a friend","友達を許す"),
    W("formulate","動","策定する","formulate a plan","計画を策定する"),
    W("found","動","設立する","found a company","会社を設立する"),
    W("frighten","動","怖がらせる","frighten a child","子供を怖がらせる"),
    W("fry","動","揚げる","fry the chicken","鶏肉を揚げる"),
    W("fulfill","動","果たす、満たす","fulfill a duty","義務を果たす"),
    W("function","動/名","機能する/機能","function properly","正しく機能する"),
    W("fund","動/名","資金提供する/資金","fund research","研究に資金提供する"),
    W("furnish","動","家具を備える","furnish a room","部屋に家具を入れる"),
    W("gain","動","得る","gain weight","体重が増える"),
    W("gaze","動","見つめる","gaze at the moon","月を見つめる"),
    W("generate","動","発生させる","generate income","収入を生む"),
    W("get","動","得る","get a job","仕事を得る"),
    W("give","動","与える","give a gift","贈り物をする"),
    W("glance","動/名","ちらりと見る/一見","glance at watch","時計をちらっと見る"),
    W("glow","動/名","輝く/輝き","glow in the dark","暗闇で光る"),
    W("go","動","行く","go home","帰宅する"),
    W("govern","動","統治する","govern a country","国を統治する"),
    W("graduate","動/名","卒業する/卒業生","graduate from university","大学を卒業する"),

    # Day 64: 抽象動作14
    W("grasp","動","つかむ、理解する","grasp the concept","概念を理解する"),
    W("grin","動/名","にっこり笑う/にっこり笑い","grin happily","嬉しそうに笑う"),
    W("grip","動/名","握る/握り","grip the bat","バットを握る"),
    W("grow","動","成長する","plants grow","植物が育つ"),
    W("guarantee","動/名","保証する/保証","guarantee quality","品質を保証する"),
    W("guard","動/名","守る/警備員","guard the gate","門を守る"),
    W("guide","動/名","案内する/ガイド","guide tourists","観光客を案内する"),
    W("hammer","動/名","ハンマーで打つ/ハンマー","hammer a nail","釘を打つ"),
    W("happen","動","起こる","accidents happen","事故が起こる"),
    W("harm","動/名","害する/害","harm the environment","環境を害する"),
    W("harvest","動/名","収穫する/収穫","harvest rice","米を収穫する"),
    W("hatch","動","孵化する","eggs hatch","卵が孵る"),
    W("hesitate","動","ためらう","hesitate to speak","話すのをためらう"),
    W("hint","動/名","ほのめかす/ヒント","hint at trouble","問題をほのめかす"),
    W("hold","動","持つ、開催する","hold a meeting","会議を開催する"),
    W("honor","動/名","敬う/名誉","honor parents","親を敬う"),
    W("hop","動","跳ぶ","frogs hop","カエルが跳ねる"),
    W("hurry","動","急ぐ","hurry up","急いで"),
    W("identify","動","特定する","identify a suspect","容疑者を特定する"),
    W("ignore","動","無視する","ignore the warning","警告を無視する"),

    # Day 65: 抽象動作15
    W("illustrate","動","図解する","illustrate a book","本に挿絵を描く"),
    W("imitate","動","真似る","imitate a bird","鳥の真似をする"),
    W("immigrate","動","移住する","immigrate to USA","アメリカに移住する"),
    W("imply","動","ほのめかす","imply a meaning","意味をほのめかす"),
    W("impose","動","課す","impose a tax","税を課す"),
    W("impress","動","印象を与える","impress the audience","聴衆に感銘を与える"),
    W("infer","動","推測する","infer meaning","意味を推測する"),
    W("inhabit","動","住む","inhabit the forest","森に住む"),
    W("inherit","動","相続する","inherit wealth","財産を相続する"),
    W("initiate","動","開始する","initiate a project","プロジェクトを開始する"),
    W("inject","動","注射する、注入する","inject medicine","薬を注射する"),
    W("inquire","動","尋ねる","inquire about prices","価格について尋ねる"),
    W("insert","動","挿入する","insert a coin","コインを入れる"),
    W("inspect","動","検査する","inspect the car","車を点検する"),
    W("instruct","動","指示する、教える","instruct students","生徒に教える"),
    W("integrate","動","統合する","integrate systems","システムを統合する"),
    W("interact","動","交流する","interact with others","他者と交流する"),
    W("interfere","動","干渉する","interfere in affairs","事件に干渉する"),
    W("interpret","動","解釈する、通訳する","interpret the data","データを解釈する"),
    W("interrupt","動","邪魔する、中断する","interrupt the speech","スピーチを中断する"),
]


# ============================================================
# 熟語・句動詞・表現（200語） - Days 66-75
# ============================================================
IDIOMS = [
    # Day 66: 句動詞1（get/give）
    W("get along with","熟","〜と仲よくする","get along with classmates","クラスメートと仲良くする"),
    W("get away","熟","逃げる、休暇を取る","get away from work","仕事から離れる"),
    W("get back","熟","戻る、取り戻す","get back home","家に戻る"),
    W("get in","熟","乗り込む、入る","get in the car","車に乗り込む"),
    W("get off","熟","降りる","get off the bus","バスを降りる"),
    W("get on","熟","乗る","get on the train","電車に乗る"),
    W("get out","熟","出る","get out of here","ここから出る"),
    W("get over","熟","乗り越える、回復する","get over a cold","風邪を治す"),
    W("get through","熟","切り抜ける、終える","get through the day","一日を乗り切る"),
    W("get to","熟","到着する、〜することができる","get to school","学校に着く"),
    W("get up","熟","起きる","get up early","早起きする"),
    W("give away","熟","あげる、配る","give away free samples","無料サンプルを配る"),
    W("give back","熟","返す","give back the book","本を返す"),
    W("give in","熟","屈する、提出する","give in to pressure","プレッシャーに屈する"),
    W("give off","熟","発する","give off light","光を発する"),
    W("give out","熟","配る、尽きる","give out flyers","チラシを配る"),
    W("give up","熟","あきらめる","give up smoking","禁煙する"),
    W("go ahead","熟","続ける、進む","Go ahead, please.","どうぞ。"),
    W("go away","熟","立ち去る","Go away!","あっち行け！"),
    W("go back","熟","戻る","go back home","家に帰る"),

    # Day 67: 句動詞2（go/come/look）
    W("go down","熟","下がる、下る","prices go down","価格が下がる"),
    W("go off","熟","鳴る、爆発する","alarm goes off","アラームが鳴る"),
    W("go on","熟","続ける、起こる","go on talking","話し続ける"),
    W("go out","熟","出かける、消える","go out for dinner","食事に出る"),
    W("go over","熟","見直す、調べる","go over the report","報告書を見直す"),
    W("go through","熟","経験する、調べる","go through hardship","苦難を経験する"),
    W("go up","熟","上がる、上る","prices go up","価格が上がる"),
    W("come across","熟","偶然出会う","come across an old friend","旧友に偶然会う"),
    W("come along","熟","一緒に来る、進む","Come along!","おいで！"),
    W("come back","熟","戻る","come back soon","すぐ戻る"),
    W("come from","熟","〜出身","come from Japan","日本出身"),
    W("come in","熟","入る","Come in, please.","お入りください。"),
    W("come on","熟","早く、頑張れ","Come on!","頑張れ！"),
    W("come out","熟","出てくる、発売される","come out of the box","箱から出る"),
    W("come up with","熟","思いつく","come up with an idea","アイデアを思いつく"),
    W("look after","熟","世話する","look after children","子供の世話をする"),
    W("look at","熟","見る","look at the sky","空を見る"),
    W("look for","熟","探す","look for keys","鍵を探す"),
    W("look forward to","熟","楽しみにする","look forward to the trip","旅行を楽しみにする"),
    W("look into","熟","調査する","look into the matter","事件を調査する"),

    # Day 68: 句動詞3（look/take）
    W("look like","熟","〜のように見える","look like rain","雨が降りそう"),
    W("look out","熟","気をつける","Look out!","気をつけて！"),
    W("look over","熟","見直す","look over the document","文書を確認する"),
    W("look up","熟","調べる、見上げる","look up a word","単語を調べる"),
    W("take after","熟","似ている","take after my father","父に似ている"),
    W("take away","熟","持ち去る、奪う","take away the dish","皿を下げる"),
    W("take back","熟","返す、撤回する","take back the words","言葉を撤回する"),
    W("take care of","熟","世話する","take care of pets","ペットの世話をする"),
    W("take in","熟","取り入れる、理解する","take in fresh air","新鮮な空気を取り込む"),
    W("take off","熟","脱ぐ、離陸する","plane takes off","飛行機が離陸する"),
    W("take on","熟","引き受ける","take on a job","仕事を引き受ける"),
    W("take out","熟","取り出す、連れ出す","take out the trash","ゴミを出す"),
    W("take over","熟","引き継ぐ","take over the business","事業を引き継ぐ"),
    W("take part in","熟","参加する","take part in a contest","コンテストに参加する"),
    W("take place","熟","行われる","take place in May","5月に開催される"),
    W("take up","熟","始める、占める","take up tennis","テニスを始める"),
    W("put away","熟","片付ける","put away toys","おもちゃを片付ける"),
    W("put off","熟","延期する","put off the meeting","会議を延期する"),
    W("put on","熟","着る、身につける","put on a coat","コートを着る"),
    W("put out","熟","消す、出す","put out the fire","火を消す"),

    # Day 69: 句動詞4（put/turn/break）
    W("put together","熟","組み立てる","put together a model","模型を組み立てる"),
    W("put up","熟","建てる、掲げる","put up a tent","テントを張る"),
    W("put up with","熟","我慢する","put up with noise","騒音に耐える"),
    W("turn down","熟","断る、音量を下げる","turn down the offer","申し出を断る"),
    W("turn in","熟","提出する、就寝する","turn in homework","宿題を提出する"),
    W("turn into","熟","変わる","turn into a butterfly","蝶になる"),
    W("turn off","熟","消す","turn off the TV","テレビを消す"),
    W("turn on","熟","つける","turn on the light","電気をつける"),
    W("turn out","熟","判明する","turn out to be true","真実と判明する"),
    W("turn over","熟","ひっくり返す","turn over the pancake","パンケーキをひっくり返す"),
    W("turn up","熟","現れる、音量を上げる","turn up the volume","音量を上げる"),
    W("break down","熟","故障する、泣き崩れる","car breaks down","車が故障する"),
    W("break in","熟","侵入する","break in the house","家に侵入する"),
    W("break into","熟","侵入する","break into a house","家に侵入する"),
    W("break off","熟","折る、中断する","break off talks","会談を中断する"),
    W("break out","熟","発生する","war breaks out","戦争が勃発する"),
    W("break up","熟","別れる、解散する","break up with him","彼と別れる"),
    W("bring about","熟","引き起こす","bring about change","変化をもたらす"),
    W("bring back","熟","持ち帰る、思い出させる","bring back memories","思い出を呼び起こす"),
    W("bring up","熟","育てる、持ち出す","bring up a child","子供を育てる"),

    # Day 70: 句動詞5
    W("call back","熟","折り返し電話する","I'll call you back.","折り返し電話します。"),
    W("call for","熟","必要とする、要求する","call for help","助けを求める"),
    W("call off","熟","中止する","call off the game","試合を中止する"),
    W("call on","熟","訪問する、頼む","call on a friend","友人を訪ねる"),
    W("call up","熟","電話する","call up the office","事務所に電話する"),
    W("carry on","熟","続ける","carry on working","働き続ける"),
    W("carry out","熟","実行する","carry out a plan","計画を実行する"),
    W("check in","熟","チェックインする","check in at the hotel","ホテルにチェックインする"),
    W("check out","熟","チェックアウト、調べる","check out of hotel","ホテルから出る"),
    W("come about","熟","起こる","How did it come about?","それはどうして起きた？"),
    W("count on","熟","頼る","count on a friend","友人を頼る"),
    W("cut down","熟","減らす、切り倒す","cut down sugar","砂糖を減らす"),
    W("cut off","熟","切り離す","cut off the supply","供給を断つ"),
    W("cut out","熟","切り抜く、やめる","cut out smoking","喫煙をやめる"),
    W("deal with","熟","対処する","deal with problems","問題に対処する"),
    W("depend on","熟","頼る、〜次第","depend on weather","天気次第"),
    W("drop by","熟","立ち寄る","drop by the cafe","カフェに立ち寄る"),
    W("drop off","熟","降ろす、減る","drop off the kids","子供を降ろす"),
    W("drop out","熟","脱落する、中退する","drop out of school","学校を中退する"),
    W("end up","熟","結局〜になる","end up alone","結局一人になる"),

    # Day 71: 句動詞6
    W("fall apart","熟","ばらばらになる","plans fall apart","計画が崩れる"),
    W("fall asleep","熟","眠りに落ちる","fall asleep early","早く眠る"),
    W("fall behind","熟","遅れる","fall behind in class","授業に遅れる"),
    W("fall down","熟","倒れる、転ぶ","fall down stairs","階段で転ぶ"),
    W("fall off","熟","落ちる","fall off the bike","自転車から落ちる"),
    W("figure out","熟","理解する、解決する","figure out the puzzle","パズルを解く"),
    W("fill in","熟","記入する、埋める","fill in the blank","空欄を埋める"),
    W("fill out","熟","記入する","fill out a form","用紙に記入する"),
    W("find out","熟","発見する、突き止める","find out the truth","真実を突き止める"),
    W("focus on","熟","集中する","focus on study","勉強に集中する"),
    W("get rid of","熟","取り除く","get rid of garbage","ゴミを処分する"),
    W("hand in","熟","提出する","hand in homework","宿題を提出する"),
    W("hand out","熟","配る","hand out leaflets","チラシを配る"),
    W("hang on","熟","待つ、しがみつく","Hang on a moment.","ちょっと待って。"),
    W("hang up","熟","電話を切る、吊るす","hang up the phone","電話を切る"),
    W("hold on","熟","待つ、しがみつく","Hold on, please.","少々お待ちを。"),
    W("keep on","熟","続ける","keep on trying","挑戦し続ける"),
    W("keep up","熟","続ける、維持する","keep up the good work","良い仕事を続けて"),
    W("knock down","熟","倒す、ノックダウンする","knock down a wall","壁を壊す"),
    W("lay off","熟","解雇する","lay off workers","労働者を解雇する"),

    # Day 72: 句動詞7
    W("let down","熟","失望させる","let me down","がっかりさせる"),
    W("look down on","熟","見下す","look down on others","他人を見下す"),
    W("look up to","熟","尊敬する","look up to him","彼を尊敬する"),
    W("make out","熟","理解する、識別する","make out his words","彼の言葉を理解する"),
    W("make up","熟","作り上げる、仲直りする","make up a story","話をでっち上げる"),
    W("make up for","熟","埋め合わせる","make up for lost time","失った時間を埋め合わせる"),
    W("pass away","熟","亡くなる","grandpa passed away","祖父が亡くなった"),
    W("pass by","熟","通り過ぎる","pass by the shop","店を通り過ぎる"),
    W("pay attention to","熟","注意を払う","pay attention to detail","細部に注意を払う"),
    W("pay back","熟","返済する、仕返しする","pay back the loan","ローンを返す"),
    W("pay off","熟","完済する、報われる","pay off the debt","借金を完済する"),
    W("pick out","熟","選び出す","pick out a gift","贈り物を選ぶ"),
    W("pick up","熟","拾う、迎えに行く","pick up trash","ゴミを拾う"),
    W("point out","熟","指摘する","point out a mistake","間違いを指摘する"),
    W("run after","熟","追いかける","run after a cat","猫を追いかける"),
    W("run away","熟","逃げる","run away from home","家出する"),
    W("run into","熟","偶然会う、ぶつかる","run into a friend","友達に偶然会う"),
    W("run out of","熟","使い果たす","run out of gas","ガス欠になる"),
    W("set up","熟","設置する、設立する","set up a company","会社を設立する"),
    W("show off","熟","見せびらかす","show off his car","車を見せびらかす"),

    # Day 73: 熟語・表現1
    W("show up","熟","現れる","show up late","遅れて現れる"),
    W("sit down","熟","座る","Please sit down.","座ってください。"),
    W("slow down","熟","減速する","slow down please","速度を落として"),
    W("speak up","熟","大声で話す、声を上げる","speak up please","もっと大きな声で"),
    W("stand by","熟","待機する、支える","stand by you","あなたを支える"),
    W("stand for","熟","表す、〜の略","USA stands for...","USAは…の略"),
    W("stand out","熟","目立つ","stand out in a crowd","群衆の中で目立つ"),
    W("stand up","熟","立ち上がる","stand up for rights","権利のため立ち上がる"),
    W("stay up","熟","起きている","stay up late","夜更かしする"),
    W("stop by","熟","立ち寄る","stop by the store","店に立ち寄る"),
    W("take off","熟","離陸する、脱ぐ","plane takes off","飛行機が離陸する"),
    W("think of","熟","考える、思い出す","think of a plan","計画を考える"),
    W("think over","熟","熟考する","think it over","じっくり考える"),
    W("throw away","熟","捨てる","throw away trash","ゴミを捨てる"),
    W("try on","熟","試着する","try on shoes","靴を試着する"),
    W("try out","熟","試す","try out a new menu","新メニューを試す"),
    W("wake up","熟","目を覚ます","wake up at 7","7時に起きる"),
    W("watch out","熟","気をつける","Watch out!","気をつけて！"),
    W("work on","熟","取り組む","work on a project","プロジェクトに取り組む"),
    W("work out","熟","運動する、解決する","work out at the gym","ジムで運動する"),

    # Day 74: 熟語・表現2
    W("according to","熟","〜によると","according to the news","ニュースによると"),
    W("a couple of","熟","2、3の","a couple of days","2、3日"),
    W("a great deal of","熟","多量の","a great deal of money","多額のお金"),
    W("a lot of","熟","たくさんの","a lot of friends","たくさんの友達"),
    W("a number of","熟","いくつかの","a number of problems","いくつかの問題"),
    W("a piece of","熟","ひとつの","a piece of cake","一切れのケーキ"),
    W("a variety of","熟","さまざまな","a variety of options","さまざまな選択肢"),
    W("after all","熟","結局","After all, we agreed.","結局、私たちは同意した。"),
    W("all of a sudden","熟","突然","all of a sudden, it rained","突然、雨が降った"),
    W("all the same","熟","それでも","All the same, thanks.","それでも、ありがとう。"),
    W("all the time","熟","いつも","all the time","いつも"),
    W("apart from","熟","〜は別として","Apart from this, all is well.","これを除けば、すべて順調。"),
    W("as a matter of fact","熟","実は","As a matter of fact, I knew.","実は、知っていた。"),
    W("as a result","熟","結果として","as a result of efforts","努力の結果"),
    W("as a rule","熟","通常は","As a rule, I sleep early.","通常、私は早く寝る。"),
    W("as far as","熟","〜の限り","as far as I know","私の知る限り"),
    W("as for","熟","〜について言えば","As for me, I agree.","私については、賛成だ。"),
    W("as if","熟","まるで〜のように","as if he knew","まるで知っているかのように"),
    W("as long as","熟","〜する限り","as long as you try","頑張る限り"),
    W("as soon as","熟","〜するとすぐに","as soon as possible","できるだけ早く"),

    # Day 75: 熟語・表現3
    W("as well as","熟","〜と同様に","English as well as math","数学と同様に英語も"),
    W("at first","熟","最初は","At first, it was hard.","最初は大変だった。"),
    W("at last","熟","ついに","At last, we won.","ついに勝った。"),
    W("at least","熟","少なくとも","at least once","少なくとも1回"),
    W("at most","熟","せいぜい","at most 10 people","せいぜい10人"),
    W("at the same time","熟","同時に","at the same time","同時に"),
    W("be about to","熟","〜しようとしている","I'm about to leave.","出かけようとしている。"),
    W("be afraid of","熟","〜を恐れる","be afraid of dogs","犬を恐れる"),
    W("be familiar with","熟","〜に詳しい","be familiar with music","音楽に詳しい"),
    W("be fond of","熟","〜が好き","be fond of cats","猫が好き"),
    W("be full of","熟","〜でいっぱい","be full of joy","喜びでいっぱい"),
    W("be good at","熟","〜が得意","be good at math","数学が得意"),
    W("be interested in","熟","〜に興味がある","be interested in art","美術に興味がある"),
    W("be made of","熟","〜でできている","be made of wood","木でできている"),
    W("be proud of","熟","〜を誇りに思う","be proud of my country","祖国を誇りに思う"),
    W("be supposed to","熟","〜することになっている","be supposed to study","勉強することになっている"),
    W("be tired of","熟","〜に飽きる","be tired of waiting","待つのに飽きる"),
    W("be used to","熟","〜に慣れている","be used to noise","騒音に慣れている"),
    W("by accident","熟","偶然に","meet by accident","偶然出会う"),
    W("by the way","熟","ところで","By the way, how are you?","ところで、元気？"),
    W("for example","熟","例えば","For example, sushi.","例えば、寿司。"),
    W("for instance","熟","例えば","For instance, apples.","例えば、リンゴ。"),
    W("for a while","熟","しばらく","Wait for a while.","しばらく待って。"),
    W("in addition","熟","加えて","In addition, it's cheap.","加えて、安い。"),
    W("in fact","熟","実は","In fact, I knew.","実は知っていた。"),
    W("in general","熟","一般的に","In general, students study.","一般的に、学生は勉強する。"),
    W("in other words","熟","言いかえれば","In other words, no.","言いかえれば、ノー。"),
    W("instead of","熟","〜の代わりに","Tea instead of coffee.","コーヒーの代わりに紅茶。"),
    W("on the other hand","熟","他方では","On the other hand, it rains.","他方では、雨が降る。"),
]


# ============================================================
# カリキュラム組み立て
# ============================================================
DAY_NAMES = [
    # Days 1-15: Verbs
    "基本動作の動詞①","基本動作の動詞②","行動・状態の動詞①","思考・感情の動詞",
    "行為・動作の動詞","知覚・調査の動詞","行動・調査の動詞","動作・状態の動詞",
    "行為・伝達の動詞","ビジネスの動詞","動作・関係の動詞","行動・継続の動詞",
    "動作・状況の動詞","動作・支援の動詞","動作・終結の動詞",
    # Days 16-20: Adjectives
    "形容詞・性質①","形容詞・程度","形容詞・感情①","形容詞・量",
    "形容詞・感情②",
    # Days 21-50: Nouns
    "自然・環境①","自然・環境②","動植物","体・健康",
    "医療・体","教育・学習","試験・成績","仕事・職業",
    "会社・組織","経済・お金","政治・社会","国際・社会問題",
    "家族・人間関係","食事・料理","飲食・買い物","旅行",
    "交通・移動","場所・地理","家・建物","物・道具",
    "科学・技術","物質・科学","動物","スポーツ",
    "芸術・娯楽","本・メディア","時間","抽象概念①",
    "抽象概念②","抽象概念③",
    # Days 51-65: Advanced Verbs
    "上級動詞①","上級動詞②","上級動詞③","上級動詞④",
    "上級動詞⑤","上級動詞⑥","上級動詞⑦","上級動詞⑧",
    "上級動詞⑨","上級動詞⑩","上級動詞⑪","上級動詞⑫",
    "上級動詞⑬","上級動詞⑭","上級動詞⑮",
    # Days 66-75: Idioms
    "句動詞①(get/give)","句動詞②(go/come/look)","句動詞③(look/take)",
    "句動詞④(put/turn/break)","句動詞⑤","句動詞⑥","句動詞⑦",
    "熟語・表現①","熟語・表現②","熟語・表現③","熟語・表現④",
]

WORDS_PER_DAY = 20


def build_curriculum():
    all_words = VERBS + ADJECTIVES + NOUNS + ADVANCED_VERBS + IDIOMS

    # 重複チェック（同じenを除外）
    seen = set()
    unique = []
    for w in all_words:
        key = w["en"].lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(w)

    print(f"Total unique words: {len(unique)}")

    days = []
    for i in range(0, len(unique), WORDS_PER_DAY):
        chunk = unique[i:i + WORDS_PER_DAY]
        di = i // WORDS_PER_DAY
        name = DAY_NAMES[di] if di < len(DAY_NAMES) else f"復習Day{di+1}"
        days.append({"name": name, "words": chunk})

    print(f"Total days: {len(days)}")
    return days


def main():
    curriculum = build_curriculum()
    json_str = json.dumps(curriculum, ensure_ascii=False, separators=(",", ":"))
    data_block = "window.CURRICULUM = " + json_str + ";"

    template = Path("template.html").read_text(encoding="utf-8")
    out = Path("index.html")
    out.write_text(template.replace("__DATA_PLACEHOLDER__", data_block), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
