#!/usr/bin/env python3
# Build CURRICULUM data: 22 days x 45 words = 990 Eiken Pre-2 words.
# Each word: (en, pos, ja, ex_en, ex_ja)  -- ja/ex_ja can include <ruby> furigana.
# The script writes JavaScript that defines window.CURRICULUM.

import json, sys

# Helper to build a word tuple.
W = lambda en,pos,ja,ex_en,ex_ja: {"en":en,"pos":pos,"ja":ja,"ex_en":ex_en,"ex_ja":ex_ja}

R = "<ruby>"  # shortcuts for furigana
def ru(k, hira):  # ru('学校','がっこう') -> ruby
    return f"<ruby>{k}<rt>{hira}</rt></ruby>"

DAYS = []

# ===== Day 1: 基本動作の動詞 =====
DAYS.append(("基本動作の動詞①", [
W("arrive","動",f"{ru('到','とう')}{ru('着','ちゃく')}する","We arrive at school at 8.",f"8{ru('時','じ')}に学校に{ru('着','つ')}く。"),
W("agree","動","さんせいする","I agree with you.","あなたにさんせい。"),
W("answer","動/名","こたえる/こたえ","Please answer.","こたえてね。"),
W("believe","動","しんじる","I believe you.","あなたをしんじる。"),
W("borrow","動","かりる","Can I borrow this?","これかりていい？"),
W("bring","動","もってくる","Bring your lunch.","おべんとうもってきて。"),
W("build","動","たてる","They build houses.","かれらは家をたてる。"),
W("carry","動","はこぶ","I'll carry it.","はこぶよ。"),
W("catch","動","つかまえる","Catch the ball!","ボールキャッチ！"),
W("change","動/名","かえる/へんか","Change your shoes.","くつをはきかえて。"),
W("choose","動","えらぶ","Choose your color.","いろをえらんで。"),
W("close","動/形","しめる/ちかい","Close the door.","ドアをしめて。"),
W("continue","動","つづける","Let's continue.","つづけよう。"),
W("cost","動/名","(費用が)かかる","How much does it cost?","いくら？"),
W("decide","動","きめる","I decided.","きめた。"),
W("drop","動","おとす","Don't drop it.","おとさないで。"),
W("enjoy","動","たのしむ","Enjoy the game.","ゲームをたのしんで。"),
W("explain","動","せつめいする","Please explain.","せつめいしてね。"),
W("finish","動","おわる","Finish your homework.","しゅくだいをおえて。"),
W("follow","動","ついていく","Follow me.","ついてきて。"),
W("forget","動","わすれる","Don't forget.","わすれないで。"),
W("happen","動","おこる","What happened?","なにがあった？"),
W("hold","動","もつ・かかえる","Hold this bag.","このカバンもって。"),
W("hurt","動","いたい/きずつける","My leg hurts.","あしがいたい。"),
W("invite","動","しょうたいする","I'll invite you.","しょうたいするね。"),
W("join","動","さんかする","Join us!","いっしょにやろう！"),
W("keep","動","たもつ","Keep it clean.","きれいにしておいて。"),
W("laugh","動","わらう","We laughed.","わらった。"),
W("learn","動","まなぶ","I learn English.","えいごをまなぶ。"),
W("leave","動","でる/はなれる","I leave at 7.","7時に出る。"),
W("lend","動","かす","Lend me a book.","本かして。"),
W("lose","動","なくす/まける","Don't lose it.","なくさないで。"),
W("miss","動","のがす/こいしい","I miss you.","あいたいよ。"),
W("move","動","うごく/ひっこす","We move next month.","らいげつひっこす。"),
W("notice","動","きづく","I didn't notice.","きづかなかった。"),
W("offer","動","もうしでる","He offered help.","てつだうとくれた。"),
W("order","動/名","ちゅうもんする","I'll order pizza.","ピザたのむね。"),
W("pay","動","はらう","I'll pay later.","あとではらう。"),
W("plan","動/名","けいかく","What's your plan?","けいかくは？"),
W("prepare","動","じゅんびする","Prepare for the test.","テストにそなえて。"),
W("receive","動","うけとる","I received a gift.","プレゼントをもらった。"),
W("remember","動","おぼえている","Remember this.","これをおぼえて。"),
W("return","動","かえる/かえす","Return the book.","本をかえして。"),
W("save","動","たすける/ためる","Save money.","おかねをためる。"),
W("share","動","わけあう","Share the cake.","ケーキをわけて。"),
]))

# ===== Day 2: コミュニケーション・調査の動詞 =====
DAYS.append(("コミュニケーションの動詞", [
W("send","動","おくる","Send a message.","メッセージおくる。"),
W("solve","動","とく(問題)","Solve this.","これをとく。"),
W("spend","動","つかう(時間/金)","Spend an hour.","1時間つかう。"),
W("suggest","動","ていあんする","I suggest tea.","おちゃがいいかも。"),
W("travel","動","りょこうする","Travel by train.","でんしゃでりょこう。"),
W("try","動","ためす/ためしてみる","Try this.","ためしてみて。"),
W("wait","動","まつ","Wait here.","ここでまって。"),
W("wear","動","きる","Wear a coat.","コートをきて。"),
W("check","動","たしかめる","Check it.","たしかめて。"),
W("collect","動","あつめる","Collect stamps.","きってをあつめる。"),
W("draw","動","えをかく","Draw a cat.","ねこをかいて。"),
W("grow","動","そだつ","Plants grow.","しょくぶつがそだつ。"),
W("introduce","動","しょうかいする","I'll introduce her.","かのじょをしょうかい。"),
W("protect","動","まもる","Protect the earth.","ちきゅうをまもる。"),
W("recommend","動","おすすめする","I recommend it.","おすすめだよ。"),
W("realize","動","きづく","I realized.","きづいた。"),
W("reply","動","へんじする","Please reply.","へんじしてね。"),
W("hope","動","のぞむ","I hope so.","そうだといいな。"),
W("wish","動","ねがう","I wish you luck.","うんがいいことをいのる。"),
W("worry","動","しんぱいする","Don't worry.","しんぱいしないで。"),
W("surprise","動","おどろかす","What a surprise!","びっくり！"),
W("appear","動","あらわれる","A rainbow appeared.","にじがでた。"),
W("recycle","動","リサイクルする","Recycle paper.","かみをリサイクル。"),
W("reduce","動","へらす","Reduce waste.","ごみをへらす。"),
W("increase","動","ふえる","Prices increase.","ねだんがあがる。"),
W("accept","動","うけいれる","Accept the gift.","プレゼントをうけとる。"),
W("advise","動","アドバイスする","She advised me.","アドバイスしてくれた。"),
W("affect","動","えいきょうする","It affects health.","けんこうにえいきょうする。"),
W("allow","動","ゆるす","Allow me to help.","てつだわせて。"),
W("announce","動","はっぴょうする","Announce the winner.","ゆうしょうしゃをはっぴょう。"),
W("apologize","動","あやまる","I apologize.","ごめんなさい。"),
W("appreciate","動","かんしゃする","I appreciate it.","かんしゃしてる。"),
W("arrange","動","ならべる/てはいする","Arrange chairs.","いすをならべる。"),
W("attend","動","しゅっせきする","Attend class.","じゅぎょうにでる。"),
W("avoid","動","さける","Avoid danger.","きけんをさける。"),
W("cause","動/名","ひきおこす/げんいん","It causes pain.","いたみをひきおこす。"),
W("celebrate","動","いわう","Celebrate the day.","お祝いしよう。"),
W("communicate","動","コミュニケーションをとる","Communicate well.","じょうずにつたえよう。"),
W("compare","動","くらべる","Compare two cars.","2台をくらべる。"),
W("complain","動","ふへいをいう","Don't complain.","もんくいわないで。"),
W("complete","動/形","かんりょうする/かんぜんな","Complete the test.","テストをおわらせて。"),
W("connect","動","つなぐ","Connect the wire.","せんをつなぐ。"),
W("consider","動","かんがえる","Consider it.","よくかんがえて。"),
W("contain","動","ふくむ","It contains sugar.","さとうがはいってる。"),
W("control","動","コントロールする","Control the volume.","おとをちょうせい。"),
]))

# ===== Day 3: 動詞③ =====
DAYS.append(("動作・つくる・はこぶの動詞", [
W("count","動","かぞえる","Count to ten.","10までかぞえて。"),
W("create","動","つくりだす","Create art.","アートをつくる。"),
W("deliver","動","とどける","Deliver the box.","はこをとどける。"),
W("describe","動","せつめいする","Describe it.","せつめいして。"),
W("design","動/名","せっけいする","Design a poster.","ポスターをデザイン。"),
W("develop","動","かいはつする","Develop a game.","ゲームをかいはつ。"),
W("disagree","動","はんたいする","I disagree.","はんたいだ。"),
W("discover","動","はっけんする","Discover treasure.","たからをはっけん。"),
W("discuss","動","はなしあう","Discuss the plan.","けいかくをはなしあう。"),
W("divide","動","わける","Divide into 4.","4つにわける。"),
W("drive","動","うんてんする","Drive a car.","車をうんてんする。"),
W("encourage","動","はげます","Encourage him.","かれをはげます。"),
W("escape","動","にげる","Escape from danger.","きけんからにげる。"),
W("exchange","動","こうかんする","Exchange gifts.","プレゼントをこうかん。"),
W("express","動","ひょうげんする","Express your idea.","かんがえをいう。"),
W("fail","動","しっぱいする","Don't fail.","しっぱいしないで。"),
W("feed","動","えさをやる","Feed the dog.","犬にえさを。"),
W("fight","動","たたかう","Fight bravely.","ゆうかんにたたかう。"),
W("fix","動","しゅうりする","Fix the bike.","じてんしゃをなおす。"),
W("fly","動","とぶ","Birds fly.","とりがとぶ。"),
W("gather","動","あつまる","Gather here.","ここにあつまって。"),
W("guess","動","すいそくする","Guess what?","あててみて。"),
W("guide","動/名","あんないする","Guide me.","あんないして。"),
W("hate","動","きらう","I hate it.","きらい。"),
W("heat","動/名","あたためる/ねつ","Heat the soup.","スープをあたためて。"),
W("hide","動","かくす","Hide the gift.","プレゼントをかくして。"),
W("hire","動","やとう","Hire him.","かれをやとう。"),
W("ignore","動","むしする","Don't ignore me.","むししないで。"),
W("imagine","動","そうぞうする","Imagine it.","そうぞうして。"),
W("improve","動","かいぜんする","Improve your skill.","ぎじゅつをみがく。"),
W("include","動","ふくめる","Include tax.","ぜいこみ。"),
W("influence","動","えいきょう","Bad influence.","わるいえいきょう。"),
W("inform","動","しらせる","Inform me.","しらせて。"),
W("invent","動","はつめいする","Invent a tool.","どうぐをはつめい。"),
W("kick","動","ける","Kick the ball.","ボールをける。"),
W("knock","動","ノックする","Knock first.","まずノックして。"),
W("lay","動","おく/ならべる","Lay it down.","おいて。"),
W("lead","動","ひきいる","Lead the team.","チームをひきいる。"),
W("lift","動","もちあげる","Lift the box.","はこをもちあげて。"),
W("mail","動/名","ゆうそうする","Mail the letter.","てがみをだす。"),
W("manage","動","かんりする","Manage time.","じかんかんり。"),
W("mean","動","いみする","What does it mean?","どういういみ？"),
W("measure","動","はかる","Measure it.","はかって。"),
W("mention","動","ふれる(話に)","He mentioned you.","あなたのこといってた。"),
W("mind","動","きにする","Don't mind.","きにしないで。"),
]))

# ===== Day 4: 動詞④ =====
DAYS.append(("動詞 ④", [
W("observe","動","かんさつする","Observe stars.","ほしをかんさつ。"),
W("own","動","もっている","I own a bike.","じてんしゃをもってる。"),
W("paint","動","ペンキをぬる","Paint the wall.","かべをぬる。"),
W("perform","動","えんじる","Perform a song.","うたをはっぴょう。"),
W("point","動","ゆびさす","Point here.","ここをさして。"),
W("practice","動","れんしゅうする","Practice piano.","ピアノのれんしゅう。"),
W("predict","動","よそうする","Predict the future.","みらいをよそう。"),
W("prefer","動","このむ","I prefer tea.","おちゃがすき。"),
W("pretend","動","ふりをする","Don't pretend.","ふりしないで。"),
W("print","動","いんさつする","Print this.","これをいんさつ。"),
W("produce","動","せいさんする","Produce milk.","ぎゅうにゅうをつくる。"),
W("promise","動","やくそくする","I promise.","やくそくする。"),
W("prove","動","しょうめいする","Prove it.","しょうめいして。"),
W("provide","動","ていきょうする","Provide food.","食事をていきょう。"),
W("publish","動","しゅっぱんする","Publish a book.","本をだす。"),
W("punish","動","ばっする","Don't punish him.","ばっしないで。"),
W("push","動","おす","Push the door.","ドアをおす。"),
W("quit","動","やめる","Quit the job.","しごとをやめる。"),
W("raise","動","あげる","Raise your hand.","てをあげて。"),
W("reach","動","とどく","Reach the top.","てっぺんへ。"),
W("react","動","はんのうする","Don't react.","はんのうしないで。"),
W("recognize","動","みわける","I recognize you.","だれかわかる。"),
W("refuse","動","ことわる","Refuse politely.","ていねいにことわる。"),
W("regret","動","こうかいする","I regret it.","こうかいしてる。"),
W("relax","動","くつろぐ","Just relax.","リラックスしよう。"),
W("rely","動","たよる","Rely on me.","たよっていいよ。"),
W("remind","動","おもいださせる","Remind me.","おもいだせて。"),
W("remove","動","とりのぞく","Remove this.","これをとって。"),
W("rent","動","ちんたいする","Rent a car.","車をかりる。"),
W("repair","動","しゅうりする","Repair the toy.","おもちゃをなおす。"),
W("repeat","動","くりかえす","Repeat after me.","くりかえして。"),
W("replace","動","とりかえる","Replace it.","とりかえて。"),
W("report","動","ほうこくする","Report the news.","ニュースをつたえる。"),
W("require","動","ひつようとする","It requires care.","ちゅういがひつよう。"),
W("rescue","動","きゅうじょする","Rescue the cat.","ねこをたすける。"),
W("respect","動","そんけいする","I respect him.","かれをそんけい。"),
W("respond","動","へんじする","Respond quickly.","はやくへんじ。"),
W("rest","動","やすむ","Rest a while.","すこしやすんで。"),
W("ride","動","のる","Ride a bike.","じてんしゃにのる。"),
W("ring","動","なる","Bells ring.","かねがなる。"),
W("roll","動","ころがる","Roll the ball.","ボールをころがして。"),
W("rule","動/名","しはい/きそく","Follow the rules.","きそくをまもる。"),
W("rush","動","いそぐ","Don't rush.","いそがないで。"),
W("satisfy","動","まんぞくさせる","Satisfy the kids.","こどもをよろこばせる。"),
W("scare","動","こわがらせる","Don't scare me.","おどかさないで。"),
]))

# ===== Day 5: 動詞⑤ =====
DAYS.append(("動詞 ⑤", [
W("search","動","さがす","Search the web.","ネットでさがす。"),
W("separate","動","わける","Separate trash.","ごみをわける。"),
W("serve","動","だす(料理)","Serve dinner.","ばんごはんをだす。"),
W("settle","動","おちつく","Settle down.","おちついて。"),
W("shake","動","ふる","Shake hands.","あくしゅしよう。"),
W("shine","動","かがやく","Stars shine.","ほしがかがやく。"),
W("shoot","動","うつ/シュート","Shoot the ball.","ボールをシュート。"),
W("shout","動","さけぶ","Don't shout.","さけばないで。"),
W("shut","動","しめる","Shut the door.","ドアをしめて。"),
W("sing","動","うたう","Sing a song.","うたをうたって。"),
W("ski","動","スキーをする","I love to ski.","スキーがすき。"),
W("smell","動","においがする","It smells good.","いいにおい。"),
W("sound","動","聞こえる","Sounds nice.","いいね。"),
W("spell","動","つづる","Spell it.","スペルは？"),
W("spread","動","ひろげる","Spread the news.","しらせる。"),
W("stand","動","たつ","Stand up.","たって。"),
W("stare","動","じっと見る","Don't stare.","じろじろ見ないで。"),
W("steal","動","ぬすむ","Don't steal.","ぬすまないで。"),
W("step","動/名","ふみだす/いっぽ","Step back.","さがって。"),
W("stick","動","くっつける","Stick it here.","ここにはって。"),
W("store","動/名","ためる/みせ","Store food.","しょくりょうをためる。"),
W("stretch","動","のばす","Stretch your legs.","あしをのばして。"),
W("succeed","動","せいこうする","I'll succeed.","せいこうするよ。"),
W("support","動","しえんする","Support the team.","チームをおうえん。"),
W("suppose","動","とおもう","I suppose so.","そうだとおもう。"),
W("swim","動","およぐ","Let's swim.","およごう。"),
W("switch","動","きりかえる","Switch off.","スイッチをきる。"),
W("teach","動","おしえる","Teach me.","おしえて。"),
W("tear","動","やぶる","Don't tear it.","やぶらないで。"),
W("tell","動","つたえる","Tell me.","おしえて。"),
W("thank","動","かんしゃする","Thank you.","ありがとう。"),
W("think","動","かんがえる","Think hard.","よくかんがえて。"),
W("throw","動","なげる","Throw the ball.","ボールをなげて。"),
W("tie","動","むすぶ","Tie your shoes.","くつのひもをむすんで。"),
W("touch","動","さわる","Don't touch.","さわらないで。"),
W("translate","動","ほんやくする","Translate this.","ほんやくして。"),
W("treat","動","あつかう/おごる","Treat well.","だいじにあつかって。"),
W("trust","動","しんらいする","Trust me.","しんじて。"),
W("understand","動","りかいする","I understand.","わかった。"),
W("upload","動","アップロードする","Upload the file.","ファイルをアップ。"),
W("vote","動","とうひょうする","Please vote.","とうひょうしてね。"),
W("wake","動","めをさます","Wake up!","おきて！"),
W("walk","動","あるく","Walk slowly.","ゆっくりあるいて。"),
W("wash","動","あらう","Wash your hands.","てをあらって。"),
W("waste","動","むだにする","Don't waste it.","むだにしないで。"),
]))

# ===== Day 6: 動詞⑥ =====
DAYS.append(("動詞 ⑥", [
W("watch","動","みる","Watch out!","きをつけて！"),
W("weigh","動","おもさをはかる","Weigh it.","おもさをはかって。"),
W("welcome","動/形","かんげいする","Welcome!","ようこそ！"),
W("win","動","かつ","Win the game.","ゲームにかつ。"),
W("wipe","動","ふく","Wipe the table.","テーブルをふいて。"),
W("wonder","動","ふしぎにおもう","I wonder why.","なぜかな。"),
W("wrap","動","つつむ","Wrap the gift.","プレゼントをつつむ。"),
W("write","動","かく","Write a letter.","てがみをかく。"),
W("yell","動","さけぶ","Don't yell.","どならないで。"),
W("lock","動","かぎをかける","Lock the door.","かぎをかけて。"),
W("type","動","タイプする","Type fast.","はやくタイプ。"),
W("swing","動","ゆれる","Swing the bat.","バットをふる。"),
W("balance","動/名","バランスをとる","Keep balance.","バランスを。"),
W("boil","動","にる/ゆでる","Boil water.","おゆをわかす。"),
W("bake","動","やく(オーブン)","Bake a cake.","ケーキをやく。"),
W("blow","動","ふく(風)","Wind blows.","風がふく。"),
W("breathe","動","いきをする","Breathe deeply.","しんこきゅう。"),
W("burn","動","もえる","Don't burn it.","やかないで。"),
W("cancel","動","とりけす","Cancel the trip.","りょこうをキャンセル。"),
W("charge","動","じゅうでんする","Charge the phone.","スマホをじゅうでん。"),
W("concentrate","動","しゅうちゅうする","Concentrate!","しゅうちゅうして！"),
W("congratulate","動","いわう","I congratulate you.","おめでとう。"),
W("contact","動","れんらくする","Contact me.","れんらくして。"),
W("contribute","動","こうけんする","Contribute money.","おかねをきふ。"),
W("cooperate","動","きょうりょくする","Cooperate well.","きょうりょくしよう。"),
W("copy","動","コピーする","Copy this page.","このページをコピー。"),
W("demand","動","ようきゅうする","I demand it.","ようきゅうする。"),
W("depend","動","たよる","Depend on you.","あなたしだい。"),
W("deserve","動","あたいする","You deserve it.","あなたにふさわしい。"),
W("dial","動","ダイヤルする","Dial the number.","ばんごうをまわして。"),
W("disappear","動","きえる","It disappeared.","きえた。"),
W("dive","動","とびこむ","Dive in.","とびこんで。"),
W("donate","動","きふする","Donate clothes.","ふくをきふ。"),
W("doubt","動","うたがう","I doubt it.","うたがう。"),
W("dress","動","ふくをきせる","Get dressed.","きがえて。"),
W("educate","動","きょういくする","Educate kids.","こどもをそだてる。"),
W("elect","動","せんぶする","Elect a leader.","リーダーをえらぶ。"),
W("employ","動","やとう","Employ workers.","ろうどうしゃをやとう。"),
W("enter","動","はいる","Enter the room.","へやにはいる。"),
W("exercise","動/名","うんどうする","Exercise daily.","まいにちうんどう。"),
W("exist","動","そんざいする","Aliens exist?","エイリアンはいる？"),
W("expand","動","ひろげる","Expand the area.","エリアをひろげる。"),
W("expect","動","きたいする","I expect rain.","あめがふりそう。"),
W("explore","動","たんけんする","Explore the cave.","どうくつをたんけん。"),
W("fade","動","あせる/きえる","Colors fade.","いろがあせる。"),
]))

# ===== Day 7: 動詞⑦ =====
DAYS.append(("動詞 ⑦", [
W("fasten","動","しっかりとめる","Fasten your belt.","ベルトをしめて。"),
W("fear","動/名","おそれる","Don't fear.","こわがらないで。"),
W("fetch","動","とってくる","Fetch the ball.","ボールをとってきて。"),
W("fill","動","みたす","Fill the cup.","カップをみたす。"),
W("freeze","動","こおる","Water freezes.","水がこおる。"),
W("gain","動","える","Gain weight.","たいじゅうがふえる。"),
W("greet","動","あいさつする","Greet guests.","おきゃくにあいさつ。"),
W("hang","動","ぶらさげる","Hang the coat.","コートをかけて。"),
W("harm","動","きずつける","Don't harm animals.","どうぶつをきずつけないで。"),
W("hesitate","動","ためらう","Don't hesitate.","ためらわないで。"),
W("hike","動","ハイキングする","Hike the mountain.","山にハイキング。"),
W("hit","動","うつ/たたく","Hit the ball.","ボールをうつ。"),
W("hop","動","とびはねる","Hop here.","ここにとんできて。"),
W("howl","動","とおぼえする","Wolves howl.","おおかみがほえる。"),
W("hurry","動","いそぐ","Hurry up!","いそいで！"),
W("identify","動","みわける","Identify the bird.","とりをみわける。"),
W("impress","動","かんどうさせる","You impressed me.","かんどうした。"),
W("indicate","動","しめす","Indicate north.","きたをさす。"),
W("inquire","動","たずねる","Inquire here.","ここでたずねて。"),
W("insist","動","しゅちょうする","I insist.","ぜったいに。"),
W("inspect","動","けんさする","Inspect the car.","車をてんけん。"),
W("install","動","インストールする","Install the app.","アプリをいれる。"),
W("invest","動","とうしする","Invest wisely.","かしこくとうし。"),
W("involve","動","まきこむ","It involves us.","わたしたちもかんけい。"),
W("iron","動","アイロンをかける","Iron the shirt.","シャツにアイロン。"),
W("issue","動/名","はっこうする/もんだい","Issue a ticket.","チケットをはっこう。"),
W("jog","動","ジョギングする","I jog daily.","まいにちジョギング。"),
W("judge","動","はんだんする","Don't judge me.","はんだんしないで。"),
W("jump","動","とぶ","Jump high.","たかくとんで。"),
W("kneel","動","ひざまずく","Kneel down.","ひざまずいて。"),
W("label","動","ラベルをはる","Label the box.","はこにラベル。"),
W("last","動","つづく","Last 5 minutes.","5分つづく。"),
W("link","動","つなぐ","Link the pages.","ページをつなぐ。"),
W("list","動/名","リストにする","List items.","アイテムをリストに。"),
W("locate","動","みつける/位置する","Locate it.","ばしょをさがして。"),
W("log","動/名","きろくする","Log in.","ログインして。"),
W("march","動","こうしんする","March forward.","まえへすすめ。"),
W("marry","動","けっこんする","They married.","けっこんした。"),
W("mark","動","しるしをつける","Mark it.","しるしをつけて。"),
W("matter","動","じゅうようだ","It matters.","だいじだよ。"),
W("melt","動","とける","Ice melts.","こおりがとける。"),
W("memorize","動","あんきする","Memorize words.","たんごをおぼえる。"),
W("mix","動","まぜる","Mix well.","よくまぜて。"),
W("model","動","モデルをする","She models.","かのじょはモデル。"),
W("nod","動","うなずく","I nodded.","うなずいた。"),
]))

# ===== Day 8: 動詞⑧（最終） =====
DAYS.append(("動詞 ⑧ 最終", [
W("note","動","メモする","Note this.","これをメモ。"),
W("obey","動","したがう","Obey rules.","きそくをまもる。"),
W("operate","動","そうさする","Operate the machine.","きかいをそうさ。"),
W("oppose","動","はんたいする","Oppose the plan.","けいかくにはんたい。"),
W("organize","動","せいりする","Organize files.","ファイルをせいり。"),
W("paste","動","はる(のり)","Paste the picture.","えをはる。"),
W("pause","動","ちょっとやめる","Pause the video.","ビデオをとめて。"),
W("peel","動","かわをむく","Peel the apple.","りんごのかわをむく。"),
W("permit","動","ゆるす","Permit me.","ゆるして。"),
W("photo","名","しゃしん","Take a photo.","しゃしんをとって。"),
W("pick","動","つむ/えらぶ","Pick a flower.","花をつむ。"),
W("pile","動","つみあげる","Pile the books.","本をつみあげる。"),
W("plug","動","プラグをさす","Plug it in.","プラグをさして。"),
W("polish","動","みがく","Polish shoes.","くつをみがく。"),
W("post","動","とうこうする","Post a photo.","しゃしんをアップ。"),
W("pour","動","つぐ","Pour water.","水をついで。"),
W("praise","動","ほめる","Praise the child.","こどもをほめる。"),
W("predict","動","よそくする","Predict weather.","てんきをよそく。"),
W("press","動","おす","Press the button.","ボタンをおす。"),
W("pretend","動","ふりをする","Stop pretending.","ふりをやめて。"),
W("print","動","プリントする","Print the page.","ページをいんさつ。"),
W("proceed","動","すすめる","Proceed slowly.","ゆっくりすすめて。"),
W("propose","動","ていあんする","Propose a plan.","けいかくをていあん。"),
W("protest","動","こうぎする","People protest.","ひとびとがこうぎ。"),
W("pull","動","ひく","Pull the rope.","ロープをひく。"),
W("purchase","動","こうにゅうする","Purchase a ticket.","チケットをかう。"),
W("quote","動","いんようする","Quote the line.","せりふをいんよう。"),
W("rate","動/名","ひょうかする","Rate the movie.","えいがをひょうか。"),
W("read","動","よむ","Read aloud.","こえに出してよんで。"),
W("recover","動","かいふくする","Recover soon.","はやくよくなって。"),
W("reflect","動","はんしゃする","Reflect light.","ひかりをはんしゃ。"),
W("regard","動","みなす","Regard him highly.","かれをそんちょう。"),
W("register","動","とうろくする","Register here.","ここでとうろく。"),
W("relate","動","かんけいする","Relate to it.","それにかんけい。"),
W("remain","動","のこる","Stay/remain calm.","おちついて。"),
W("repair","動","しゅうりする","Repair the bike.","じてんしゃをしゅうり。"),
W("retire","動","いんたいする","Retire at 60.","60でいんたい。"),
W("review","動","ふくしゅう","Review notes.","ノートをふくしゅう。"),
W("reward","動","ほうびをあげる","Reward kids.","ごほうび。"),
W("ride","動","のる","Ride a horse.","うまにのる。"),
W("roast","動","ローストする","Roast chicken.","チキンをやく。"),
W("row","動","こぐ","Row the boat.","ボートをこぐ。"),
W("save","動","セーブする","Save the file.","ファイルをほぞん。"),
W("scan","動","スキャンする","Scan the code.","コードをスキャン。"),
W("schedule","動/名","よていする","Schedule a meeting.","ミーティングをよてい。"),
]))

# ===== Day 9: けいようし① =====
DAYS.append(("けいようし ①", [
W("afraid","形","こわい","I'm afraid.","こわい。"),
W("angry","形","おこっている","Mom is angry.","ママおこってる。"),
W("beautiful","形","うつくしい","Beautiful flower.","きれいな花。"),
W("big","形","おおきい","Big tree.","おおきな木。"),
W("busy","形","いそがしい","Busy day.","いそがしい日。"),
W("careful","形","きをつけて","Be careful.","きをつけて。"),
W("cheap","形","やすい","Cheap bag.","やすいカバン。"),
W("clean","形","きれい","Clean room.","きれいな部屋。"),
W("cold","形","つめたい","Cold water.","つめたい水。"),
W("cute","形","かわいい","Cute baby.","かわいいあかちゃん。"),
W("dangerous","形","きけん","Dangerous road.","きけんなみち。"),
W("dark","形","くらい","Dark room.","くらい部屋。"),
W("deep","形","ふかい","Deep ocean.","ふかいうみ。"),
W("delicious","形","おいしい","Delicious cake.","おいしいケーキ。"),
W("different","形","ちがう","Different colors.","ちがういろ。"),
W("difficult","形","むずかしい","Difficult test.","むずかしいテスト。"),
W("dirty","形","きたない","Dirty shoes.","きたないくつ。"),
W("dry","形","かわいた","Dry towel.","かわいたタオル。"),
W("easy","形","かんたん","Easy task.","かんたんなしごと。"),
W("expensive","形","たかい(値段)","Expensive bag.","たかいカバン。"),
W("famous","形","ゆうめい","Famous singer.","ゆうめいなかしゅ。"),
W("fast","形/副","はやい","Fast car.","はやい車。"),
W("free","形","ひま/ただ","Free time.","ひまな時間。"),
W("fresh","形","しんせん","Fresh fruit.","しんせんなくだもの。"),
W("friendly","形","したしみのある","Friendly dog.","したしみある犬。"),
W("full","形","いっぱい","Full bottle.","いっぱいのびん。"),
W("funny","形","おもしろい","Funny joke.","おもしろいジョーク。"),
W("happy","形","しあわせ","Happy day.","しあわせな日。"),
W("hard","形/副","かたい/たいへん","Hard work.","たいへんなしごと。"),
W("heavy","形","おもい","Heavy bag.","おもいカバン。"),
W("hot","形","あつい","Hot soup.","あついスープ。"),
W("hungry","形","おなかがすいた","I'm hungry.","おなかすいた。"),
W("important","形","だいじ","Important thing.","だいじなこと。"),
W("interesting","形","おもしろい","Interesting book.","おもしろい本。"),
W("kind","形","しんせつ","Kind teacher.","やさしい先生。"),
W("large","形","おおきい","Large size.","おおきいサイズ。"),
W("late","形","おそい","Late bus.","おそいバス。"),
W("light","形","かるい/明るい","Light bag.","かるいカバン。"),
W("lonely","形","さみしい","Feel lonely.","さみしい。"),
W("loud","形","うるさい","Loud noise.","うるさいおと。"),
W("new","形","あたらしい","New game.","あたらしいゲーム。"),
W("old","形","ふるい/年とった","Old book.","ふるい本。"),
W("popular","形","にんきがある","Popular song.","にんきのうた。"),
W("quiet","形","しずか","Quiet park.","しずかなこうえん。"),
W("rich","形","おかねもち","Rich man.","おかねもち。"),
]))

# ===== Day 10: けいようし② =====
DAYS.append(("けいようし ② ＆ 副詞", [
W("sad","形","かなしい","Sad story.","かなしい話。"),
W("safe","形","あんぜん","Safe place.","あんぜんなばしょ。"),
W("short","形","みじかい","Short hair.","みじかいかみ。"),
W("sick","形","びょうき","I'm sick.","びょうき。"),
W("simple","形","かんたん","Simple rule.","かんたんなルール。"),
W("slow","形","おそい","Slow turtle.","おそいかめ。"),
W("small","形","ちいさい","Small dog.","ちいさい犬。"),
W("smart","形","かしこい","Smart kid.","かしこい子。"),
W("soft","形","やわらかい","Soft pillow.","やわらかいまくら。"),
W("special","形","とくべつ","Special day.","とくべつな日。"),
W("strong","形","つよい","Strong wind.","つよい風。"),
W("sweet","形","あまい","Sweet candy.","あまいキャンディ。"),
W("tall","形","せがたかい","Tall tree.","せがたかい木。"),
W("thick","形","あつい(厚)","Thick book.","あつい本。"),
W("thin","形","うすい/やせた","Thin paper.","うすいかみ。"),
W("tired","形","つかれた","I'm tired.","つかれた。"),
W("useful","形","やくにたつ","Useful tool.","やくにたつ。"),
W("warm","形","あたたかい","Warm coat.","あたたかいコート。"),
W("weak","形","よわい","Weak signal.","よわい電波。"),
W("wet","形","ぬれた","Wet floor.","ぬれたゆか。"),
W("wild","形","やせい","Wild animal.","やせいどうぶつ。"),
W("young","形","わかい","Young boy.","わかい男の子。"),
W("brave","形","ゆうかんな","Brave soldier.","ゆうかんなへいし。"),
W("calm","形","おだやか","Calm sea.","おだやかなうみ。"),
W("clever","形","かしこい","Clever fox.","かしこいきつね。"),
W("common","形","ふつう","Common name.","よくあるなまえ。"),
W("confident","形","じしんがある","Confident smile.","じしんあるえがお。"),
W("curious","形","こうきしんがある","Curious cat.","こうきしんねこ。"),
W("daily","形","まいにちの","Daily routine.","まいにちのしゅうかん。"),
W("eager","形","ねっしんな","Eager to learn.","まなびたがってる。"),
W("elderly","形","おとしより","Elderly woman.","おとしよりの女性。"),
W("empty","形","からの","Empty box.","からのはこ。"),
W("equal","形","おなじ","Equal rights.","びょうどう。"),
W("excellent","形","すばらしい","Excellent work.","すばらしい。"),
W("exciting","形","ワクワクする","Exciting game.","ワクワクするゲーム。"),
W("fair","形","こうへい","Fair rule.","こうへいなルール。"),
W("favorite","形","おきにいり","Favorite color.","おきにいりのいろ。"),
W("foreign","形","がいこくの","Foreign country.","がいこく。"),
W("gentle","形","やさしい","Gentle touch.","やさしいてざわり。"),
W("glad","形","うれしい","Glad to see you.","あえてうれしい。"),
W("global","形","せかいの","Global issue.","せかいのもんだい。"),
W("helpful","形","やくにたつ","Helpful advice.","やくにたつアドバイス。"),
W("honest","形","しょうじき","Honest boy.","しょうじきな子。"),
W("huge","形","とてつもなく大きい","Huge cake.","でっかいケーキ。"),
W("ideal","形","りそうてき","Ideal weather.","りそうてきな天気。"),
]))

# ===== Day 11: けいようし③＆副詞 =====
DAYS.append(("けいようし ③ ＆ 副詞", [
W("ill","形","びょうきの","Feel ill.","びょうき。"),
W("impossible","形","ふかのう","It's impossible.","ふかのう。"),
W("incredible","形","しんじられない","Incredible view!","すごいけしき！"),
W("informal","形","くだけた","Informal party.","カジュアルなパーティ。"),
W("intelligent","形","ちてきな","Intelligent dog.","かしこい犬。"),
W("international","形","こくさいてき","International event.","こくさいイベント。"),
W("lazy","形","なまけ","Lazy cat.","なまけねこ。"),
W("local","形","じもとの","Local food.","じもとの食べ物。"),
W("lovely","形","すてきな","Lovely dress.","すてきなドレス。"),
W("lucky","形","うんがいい","Lucky day.","うんのいい日。"),
W("main","形","おもな","Main idea.","しゅよう。"),
W("modern","形","げんだい","Modern art.","げんだいアート。"),
W("mysterious","形","しんぴ","Mysterious story.","ふしぎな話。"),
W("narrow","形","せまい","Narrow road.","せまい道。"),
W("native","形","ほんばの","Native speaker.","ほんばのひと。"),
W("natural","形","しぜんの","Natural food.","てんねん食。"),
W("nervous","形","ドキドキする","I'm nervous.","ドキドキする。"),
W("noisy","形","うるさい","Noisy room.","うるさい部屋。"),
W("normal","形","ふつう","Normal day.","ふつうの日。"),
W("obvious","形","あきらか","Obvious answer.","あきらか。"),
W("official","形","こうしき","Official letter.","こうしきな手紙。"),
W("original","形","オリジナル","Original idea.","オリジナル。"),
W("painful","形","いたい","Painful injury.","いたいけが。"),
W("peaceful","形","へいわな","Peaceful village.","へいわな村。"),
W("perfect","形","かんぺき","Perfect score.","まんてん。"),
W("polite","形","ていねい","Polite child.","ていねいな子。"),
W("poor","形","まずしい/かわいそう","Poor cat.","かわいそうなねこ。"),
W("powerful","形","つよい/きょうりょく","Powerful engine.","パワフルなエンジン。"),
W("private","形","プライベート","Private room.","こしつ。"),
W("proud","形","ほこりがある","Proud parents.","じまんのおや。"),
W("quick","形","すばやい","Quick run.","すばやいラン。"),
W("rare","形","まれ","Rare animal.","まれなどうぶつ。"),
W("ready","形","じゅんびかんりょう","Ready?","じゅんびOK？"),
W("real","形","ほんもの","Real gold.","ほんもののきん。"),
W("regular","形","ていきの","Regular size.","ふつうサイズ。"),
W("responsible","形","せきにんがある","Responsible kid.","せきにんかんあり。"),
W("rough","形","あらい","Rough surface.","あらいひょうめん。"),
W("rude","形","ぶれい","Rude behavior.","ぶれいなたいど。"),
W("silly","形","ばかげた","Silly idea.","ばかげたアイデア。"),
W("similar","形","にている","Similar style.","にているスタイル。"),
W("always","副","いつも","Always smile.","いつもえがお。"),
W("sometimes","副","ときどき","Sometimes I run.","ときどきはしる。"),
W("usually","副","たいてい","I usually walk.","たいていあるく。"),
W("often","副","よく","I often read.","よく本をよむ。"),
W("never","副","けっして〜ない","Never give up.","あきらめない。"),
]))

# ===== Day 12: 名詞: 学校・勉強 =====
DAYS.append(("名詞: 学校・勉強", [
W("classroom","名","きょうしつ","Big classroom.","おおきなきょうしつ。"),
W("homework","名","しゅくだい","Do homework.","しゅくだいする。"),
W("science","名","りか","Science class.","りかのじゅぎょう。"),
W("history","名","れきし","Japanese history.","にほんし。"),
W("language","名","ことば","Foreign language.","がいこくご。"),
W("library","名","としょかん","Quiet library.","しずかなとしょかん。"),
W("dictionary","名","じしょ","Use a dictionary.","じしょをつかう。"),
W("teacher","名","せんせい","Math teacher.","すうがくの先生。"),
W("student","名","せいと","High school student.","こうこうせい。"),
W("school","名","がっこう","Go to school.","学校へいく。"),
W("subject","名","かもく","Favorite subject.","おきにいりのかもく。"),
W("test","名","テスト","Math test.","すうがくテスト。"),
W("exam","名","しけん","Final exam.","きまつしけん。"),
W("textbook","名","きょうかしょ","Open the textbook.","きょうかしょをあけて。"),
W("notebook","名","ノート","New notebook.","あたらしいノート。"),
W("pencil","名","えんぴつ","Sharp pencil.","とがったえんぴつ。"),
W("eraser","名","けしごむ","Lose the eraser.","けしゴムなくした。"),
W("ruler","名","じょうぎ","Use a ruler.","じょうぎをつかう。"),
W("blackboard","名","こくばん","Write on the blackboard.","こくばんにかく。"),
W("chalk","名","チョーク","White chalk.","白いチョーク。"),
W("desk","名","つくえ","Clean desk.","きれいなつくえ。"),
W("chair","名","いす","Comfy chair.","ふかふかのいす。"),
W("schedule","名","じかんわり","Class schedule.","じゅぎょうのよてい。"),
W("lesson","名","レッスン","Piano lesson.","ピアノレッスン。"),
W("class","名","クラス","Math class.","すうがくのクラス。"),
W("grade","名","せいせき/学年","Good grade.","いいせいせき。"),
W("score","名","てんすう","High score.","こうとくてん。"),
W("question","名","しつもん","Good question.","いいしつもん。"),
W("answer","名","こたえ","Right answer.","せいかい。"),
W("essay","名","エッセイ","Write an essay.","エッセイをかく。"),
W("speech","名","スピーチ","Give a speech.","スピーチする。"),
W("project","名","プロジェクト","Group project.","グループプロジェクト。"),
W("research","名/動","けんきゅう","Do research.","けんきゅうする。"),
W("experiment","名","じっけん","Science experiment.","りかじっけん。"),
W("club","名","クラブ","Tennis club.","テニスクラブ。"),
W("uniform","名","せいふく","School uniform.","せいふく。"),
W("locker","名","ロッカー","School locker.","学校のロッカー。"),
W("bell","名","ベル","School bell.","学校のチャイム。"),
W("art","名","びじゅつ","Art class.","びじゅつのじゅぎょう。"),
W("math","名","さんすう/すうがく","Math problem.","すうがくのもんだい。"),
W("English","名","えいご","Learn English.","えいごをまなぶ。"),
W("Japanese","名","にほんご","Speak Japanese.","にほんごをはなす。"),
W("music","名","おんがく","Music class.","おんがくのクラス。"),
W("PE","名","たいいく","PE lesson.","たいいくのじゅぎょう。"),
W("group","名","グループ","My group.","わたしのグループ。"),
]))

# ===== Day 13: 名詞: 食べ物・飲み物 =====
DAYS.append(("名詞: 食べもの・飲みもの", [
W("breakfast","名","あさごはん","Eat breakfast.","あさごはんを食べる。"),
W("lunch","名","ひるごはん","Have lunch.","ひるごはんを食べる。"),
W("dinner","名","ばんごはん","Family dinner.","かぞくでばんごはん。"),
W("vegetable","名","やさい","Eat vegetables.","やさいを食べて。"),
W("fruit","名","くだもの","Sweet fruit.","あまいくだもの。"),
W("meat","名","にく","Cook meat.","にくをやく。"),
W("bread","名","パン","Fresh bread.","やきたてのパン。"),
W("juice","名","ジュース","Apple juice.","りんごジュース。"),
W("snack","名","おやつ","Healthy snack.","ヘルシーおやつ。"),
W("restaurant","名","レストラン","Japanese restaurant.","にほんりょうりや。"),
W("cake","名","ケーキ","Birthday cake.","たんじょうびケーキ。"),
W("cookie","名","クッキー","Choco cookie.","チョコクッキー。"),
W("candy","名","あめ","Sweet candy.","あまいあめ。"),
W("chocolate","名","チョコ","Dark chocolate.","ダークチョコ。"),
W("ice cream","名","アイス","Vanilla ice cream.","バニラアイス。"),
W("rice","名","ごはん","Steamed rice.","むしごはん。"),
W("noodle","名","めん","Hot noodles.","あつあつのめん。"),
W("pasta","名","パスタ","Tomato pasta.","トマトパスタ。"),
W("soup","名","スープ","Hot soup.","あついスープ。"),
W("salad","名","サラダ","Fresh salad.","しんせんなサラダ。"),
W("egg","名","たまご","Boiled egg.","ゆでたまご。"),
W("milk","名","ぎゅうにゅう","Cold milk.","つめたいぎゅうにゅう。"),
W("water","名","みず","Drink water.","みずをのむ。"),
W("tea","名","おちゃ","Green tea.","おちゃ。"),
W("coffee","名","コーヒー","Black coffee.","ブラックコーヒー。"),
W("sugar","名","さとう","Add sugar.","さとうをたす。"),
W("salt","名","しお","Less salt.","しおすくなめ。"),
W("pepper","名","こしょう","Black pepper.","くろこしょう。"),
W("butter","名","バター","Soft butter.","やわらかいバター。"),
W("cheese","名","チーズ","Yellow cheese.","きいろいチーズ。"),
W("apple","名","りんご","Red apple.","あかいりんご。"),
W("banana","名","バナナ","Yellow banana.","きいろいバナナ。"),
W("orange","名","オレンジ","Sweet orange.","あまいオレンジ。"),
W("strawberry","名","いちご","Strawberry jam.","いちごジャム。"),
W("grape","名","ぶどう","Purple grapes.","むらさきのぶどう。"),
W("watermelon","名","すいか","Big watermelon.","おおきいすいか。"),
W("tomato","名","トマト","Red tomato.","あかいトマト。"),
W("carrot","名","にんじん","Orange carrot.","オレンジのにんじん。"),
W("potato","名","じゃがいも","Boiled potato.","ゆでじゃが。"),
W("onion","名","たまねぎ","Cut onion.","たまねぎをきる。"),
W("chicken","名","とり","Fried chicken.","からあげ。"),
W("beef","名","ぎゅうにく","Grilled beef.","ぎゅうのやきにく。"),
W("pork","名","ぶたにく","Pork dish.","ぶたにくりょうり。"),
W("fish","名","さかな","Cook fish.","さかなを焼く。"),
W("dessert","名","デザート","Sweet dessert.","あまいデザート。"),
]))

# ===== Day 14: 名詞: 人・しごと =====
DAYS.append(("名詞: 人・しごと", [
W("doctor","名","いしゃ","See a doctor.","いしゃに行く。"),
W("nurse","名","かんごし","Kind nurse.","やさしいかんごし。"),
W("farmer","名","のうか","Hard-working farmer.","がんばるのうか。"),
W("police","名","けいさつ","Call police.","けいさつをよぶ。"),
W("singer","名","かしゅ","Pop singer.","ポップしんがー。"),
W("writer","名","さっか","Famous writer.","ゆうめいさっか。"),
W("artist","名","げいじゅつか","Talented artist.","さいのうあるアーティスト。"),
W("neighbor","名","となりのひと","Friendly neighbor.","やさしいおとなり。"),
W("family","名","かぞく","Big family.","だいかぞく。"),
W("friend","名","ともだち","Best friend.","しんゆう。"),
W("father","名","ちち","My father.","わたしのちち。"),
W("mother","名","はは","Loving mother.","やさしいはは。"),
W("brother","名","あに/おとうと","Older brother.","あに。"),
W("sister","名","あね/いもうと","Little sister.","いもうと。"),
W("grandfather","名","おじいちゃん","Old grandfather.","おじいちゃん。"),
W("grandmother","名","おばあちゃん","Sweet grandmother.","やさしいおばあちゃん。"),
W("uncle","名","おじ","My uncle.","わたしのおじ。"),
W("aunt","名","おば","Cool aunt.","おば。"),
W("cousin","名","いとこ","Best cousin.","だいすきないとこ。"),
W("baby","名","あかちゃん","Cute baby.","かわいいあかちゃん。"),
W("child","名","こども","Happy child.","しあわせなこども。"),
W("man","名","おとこ","Tall man.","せがたかいおとこ。"),
W("woman","名","おんな","Kind woman.","やさしいおんな。"),
W("boy","名","男の子","Young boy.","わかい男の子。"),
W("girl","名","女の子","Smart girl.","かしこい女の子。"),
W("people","名","ひとびと","Many people.","たくさんのひと。"),
W("dentist","名","はいしゃ","Visit a dentist.","はいしゃへ。"),
W("scientist","名","かがくしゃ","Famous scientist.","かがくしゃ。"),
W("engineer","名","ぎし","Software engineer.","ソフトエンジニア。"),
W("astronaut","名","うちゅうひこうし","Brave astronaut.","ゆうかんなうちゅうひこうし。"),
W("athlete","名","せんしゅ","Top athlete.","いちりゅうせんしゅ。"),
W("actor","名","はいゆう","Famous actor.","ゆうめいはいゆう。"),
W("actress","名","じょゆう","Pretty actress.","きれいなじょゆう。"),
W("musician","名","おんがくか","Great musician.","すごいおんがくか。"),
W("director","名","かんとく","Movie director.","えいがかんとく。"),
W("president","名","しゃちょう/だいとうりょう","School president.","校長。"),
W("officer","名","しょうこう/警官","Police officer.","けいさつかん。"),
W("clerk","名","てんいん","Friendly clerk.","しんせつなてんいん。"),
W("driver","名","うんてんしゅ","Bus driver.","バスのうんてんしゅ。"),
W("pilot","名","パイロット","Pilot of a plane.","ひこうきのパイロット。"),
W("captain","名","せんちょう/きゃぷてん","Team captain.","キャプテン。"),
W("guest","名","おきゃくさま","Welcome the guest.","おきゃくさまをかんげい。"),
W("stranger","名","しらないひと","Talk to stranger.","しらないひとと話す。"),
W("partner","名","パートナー","Dance partner.","ダンスパートナー。"),
W("expert","名","エキスパート","Math expert.","すうがくのプロ。"),
]))

# ===== Day 15: 名詞: 自然・天気 =====
DAYS.append(("名詞: 自然・天気", [
W("mountain","名","やま","High mountain.","たかい山。"),
W("river","名","かわ","Long river.","ながい川。"),
W("ocean","名","うみ","Blue ocean.","あおいうみ。"),
W("forest","名","もり","Dark forest.","くらいもり。"),
W("island","名","しま","Small island.","小さいしま。"),
W("earth","名","ちきゅう","Save the Earth.","ちきゅうをまもる。"),
W("weather","名","てんき","Nice weather.","いいてんき。"),
W("snow","名","ゆき","White snow.","白いゆき。"),
W("wind","名","かぜ","Strong wind.","つよい風。"),
W("sky","名","そら","Blue sky.","あおいそら。"),
W("sun","名","たいよう","Bright sun.","まぶしいたいよう。"),
W("moon","名","つき","Full moon.","まんげつ。"),
W("star","名","ほし","Twinkling star.","きらめくほし。"),
W("cloud","名","くも","White cloud.","白いくも。"),
W("rain","名","あめ","Heavy rain.","おおあめ。"),
W("storm","名","あらし","Big storm.","おおあらし。"),
W("thunder","名","かみなり","Loud thunder.","おおきなかみなり。"),
W("lightning","名","いなずま","Bright lightning.","あかるいいなずま。"),
W("typhoon","名","たいふう","Typhoon coming.","たいふうがくる。"),
W("rainbow","名","にじ","Beautiful rainbow.","きれいなにじ。"),
W("flood","名","こうずい","Flood damage.","こうずいひがい。"),
W("earthquake","名","じしん","Big earthquake.","おおきなじしん。"),
W("volcano","名","かざん","Active volcano.","かつかざん。"),
W("desert","名","さばく","Hot desert.","あついさばく。"),
W("jungle","名","ジャングル","Deep jungle.","おくぶかいジャングル。"),
W("hill","名","おか","Green hill.","みどりのおか。"),
W("valley","名","たに","Deep valley.","ふかいたに。"),
W("lake","名","みずうみ","Calm lake.","しずかなみずうみ。"),
W("pond","名","いけ","Small pond.","ちいさいいけ。"),
W("waterfall","名","たき","Tall waterfall.","たかいたき。"),
W("beach","名","ビーチ","Sandy beach.","すなはま。"),
W("coast","名","かいがん","Rocky coast.","いわのかいがん。"),
W("nature","名","しぜん","Love nature.","しぜんがすき。"),
W("environment","名","かんきょう","Protect the environment.","かんきょうをまもる。"),
W("season","名","きせつ","Four seasons.","しきせつ。"),
W("spring","名","はる","Warm spring.","あたたかいはる。"),
W("summer","名","なつ","Hot summer.","あついなつ。"),
W("autumn","名","あき","Cool autumn.","すずしいあき。"),
W("winter","名","ふゆ","Cold winter.","さむいふゆ。"),
W("temperature","名","おんど","High temperature.","たかいきおん。"),
W("climate","名","きこう","Tropical climate.","ねったいきこう。"),
W("smoke","名","けむり","Black smoke.","くろいけむり。"),
W("fog","名","きり","Thick fog.","こいきり。"),
W("ice","名","こおり","Cold ice.","つめたいこおり。"),
W("rock","名","いわ","Big rock.","おおきないわ。"),
]))

# ===== Day 16: 名詞: 動物・植物・もの =====
DAYS.append(("名詞: どうぶつ・しょくぶつ・もの", [
W("animal","名","どうぶつ","Wild animal.","やせいどうぶつ。"),
W("butterfly","名","ちょうちょ","Yellow butterfly.","きいろいちょう。"),
W("insect","名","こんちゅう","Tiny insect.","小さなこんちゅう。"),
W("plant","名","しょくぶつ","Green plant.","みどりのしょくぶつ。"),
W("flower","名","花","Pretty flower.","きれいな花。"),
W("tree","名","木","Old tree.","古い木。"),
W("grass","名","くさ","Green grass.","みどりのくさ。"),
W("leaf","名","はっぱ","Red leaf.","あかいはっぱ。"),
W("rose","名","バラ","Red rose.","あかいバラ。"),
W("seed","名","たね","Plant a seed.","たねをまく。"),
W("dog","名","いぬ","Pet dog.","ペットの犬。"),
W("cat","名","ねこ","Black cat.","くろいねこ。"),
W("bird","名","とり","Sing bird.","うたうとり。"),
W("fish","名","さかな","Goldfish.","きんぎょ。"),
W("mouse","名","ねずみ","Tiny mouse.","ちいさいねずみ。"),
W("rabbit","名","うさぎ","Cute rabbit.","かわいいうさぎ。"),
W("horse","名","うま","Brown horse.","ちゃいろいうま。"),
W("cow","名","うし","Big cow.","おおきいうし。"),
W("pig","名","ぶた","Pink pig.","ピンクのぶた。"),
W("sheep","名","ひつじ","White sheep.","しろいひつじ。"),
W("monkey","名","さる","Smart monkey.","かしこいさる。"),
W("elephant","名","ぞう","Huge elephant.","でっかいぞう。"),
W("lion","名","ライオン","King lion.","ライオンの王。"),
W("tiger","名","とら","Striped tiger.","しまもようのとら。"),
W("bear","名","くま","Brown bear.","ちゃいろいくま。"),
W("wolf","名","おおかみ","Wild wolf.","やせいのおおかみ。"),
W("fox","名","きつね","Quick fox.","すばしっこいきつね。"),
W("snake","名","へび","Long snake.","ながいへび。"),
W("frog","名","かえる","Jumping frog.","とぶかえる。"),
W("dolphin","名","いるか","Smart dolphin.","かしこいいるか。"),
W("whale","名","くじら","Big whale.","おおきなくじら。"),
W("shark","名","さめ","Scary shark.","こわいさめ。"),
W("penguin","名","ペンギン","Cute penguin.","かわいいペンギン。"),
W("ant","名","あり","Working ant.","はたらきあり。"),
W("bee","名","はち","Busy bee.","いそがしいハチ。"),
W("spider","名","くも(虫)","Big spider.","おおきいクモ。"),
W("machine","名","きかい","New machine.","あたらしいきかい。"),
W("computer","名","パソコン","Use computer.","パソコンをつかう。"),
W("camera","名","カメラ","Old camera.","ふるいカメラ。"),
W("newspaper","名","しんぶん","Read newspaper.","しんぶんをよむ。"),
W("present","名","プレゼント","Birthday present.","たんじょうびプレゼント。"),
W("gift","名","おくりもの","Special gift.","とくべつなおくりもの。"),
W("ball","名","ボール","Round ball.","まるいボール。"),
W("toy","名","おもちゃ","Plastic toy.","プラスチックのおもちゃ。"),
W("doll","名","にんぎょう","Old doll.","ふるい人形。"),
]))

# ===== Day 17: 名詞: まち・たてもの =====
DAYS.append(("名詞: 町・建物", [
W("airport","名","くうこう","International airport.","こくさいくうこう。"),
W("station","名","えき","Train station.","えき。"),
W("hospital","名","びょういん","Big hospital.","おおきいびょういん。"),
W("hotel","名","ホテル","Nice hotel.","いいホテル。"),
W("museum","名","はくぶつかん","Visit museum.","はくぶつかん。"),
W("bank","名","ぎんこう","Big bank.","ぎんこう。"),
W("factory","名","こうじょう","Car factory.","車のこうじょう。"),
W("office","名","じむしょ","My office.","じむしょ。"),
W("city","名","とし","Big city.","だいとし。"),
W("country","名","くに","Foreign country.","がいこく。"),
W("park","名","こうえん","Local park.","じもとのこうえん。"),
W("zoo","名","どうぶつえん","Zoo trip.","どうぶつえん。"),
W("aquarium","名","すいぞくかん","Visit aquarium.","すいぞくかん。"),
W("temple","名","てら","Old temple.","ふるいてら。"),
W("shrine","名","じんじゃ","Visit shrine.","じんじゃへ。"),
W("church","名","きょうかい","Old church.","ふるいきょうかい。"),
W("castle","名","しろ","Stone castle.","いしのしろ。"),
W("tower","名","とう","Tokyo Tower.","とうきょうタワー。"),
W("bridge","名","はし","Long bridge.","ながいはし。"),
W("road","名","みち","Wide road.","ひろいみち。"),
W("street","名","とおり","Busy street.","にぎやかなとおり。"),
W("path","名","こみち","Forest path.","もりのこみち。"),
W("highway","名","こうそく","Highway speed.","こうそくスピード。"),
W("village","名","むら","Small village.","ちいさなむら。"),
W("town","名","まち","Quiet town.","しずかなまち。"),
W("supermarket","名","スーパー","Local supermarket.","じもとのスーパー。"),
W("store","名","みせ","Grocery store.","しょくりょうてん。"),
W("shop","名","ショップ","Toy shop.","おもちゃ屋さん。"),
W("mall","名","モール","Shopping mall.","ショッピングモール。"),
W("market","名","しじょう","Fish market.","うおいちば。"),
W("library","名","としょかん","Quiet library.","しずかなとしょかん。"),
W("theater","名","げきじょう","Movie theater.","えいがかん。"),
W("cinema","名","えいがかん","Go to cinema.","えいがかんへ。"),
W("stadium","名","スタジアム","Soccer stadium.","サッカースタジアム。"),
W("gym","名","たいいくかん","School gym.","学校のたいいくかん。"),
W("swimming pool","名","プール","Outdoor pool.","やがいプール。"),
W("playground","名","あそびば","Fun playground.","たのしいあそびば。"),
W("garage","名","ガレージ","Two-car garage.","2台ガレージ。"),
W("garden","名","にわ","Pretty garden.","きれいなにわ。"),
W("yard","名","にわ/ヤード","Front yard.","まえにわ。"),
W("entrance","名","いりぐち","Main entrance.","メインゲート。"),
W("exit","名","でぐち","Exit door.","でぐちのドア。"),
W("elevator","名","エレベーター","Take the elevator.","エレベーターでいく。"),
W("escalator","名","エスカレーター","Use escalator.","エスカレーター。"),
W("corner","名","かど","Street corner.","まちかど。"),
]))

# ===== Day 18: 名詞: 家・もの =====
DAYS.append(("名詞: 家・身のまわりのもの", [
W("kitchen","名","だいどころ","Clean kitchen.","きれいなだいどころ。"),
W("bathroom","名","おふろば","Use bathroom.","おふろば。"),
W("bedroom","名","しんしつ","My bedroom.","わたしのしんしつ。"),
W("living room","名","リビング","Big living room.","おおきいリビング。"),
W("window","名","まど","Open window.","あいているまど。"),
W("floor","名","ゆか","Wooden floor.","木のゆか。"),
W("ceiling","名","てんじょう","High ceiling.","たかいてんじょう。"),
W("wall","名","かべ","White wall.","しろいかべ。"),
W("door","名","ドア","Wooden door.","木のドア。"),
W("roof","名","やね","Red roof.","あかいやね。"),
W("clock","名","とけい","Wall clock.","かべのとけい。"),
W("watch","名","うで時計","New watch.","あたらしいうで時計。"),
W("key","名","かぎ","House key.","いえのかぎ。"),
W("map","名","ちず","World map.","せかいちず。"),
W("calendar","名","カレンダー","Wall calendar.","かべのカレンダー。"),
W("phone","名","でんわ","Smart phone.","スマホ。"),
W("mirror","名","かがみ","Big mirror.","おおきなかがみ。"),
W("table","名","テーブル","Long table.","ながいテーブル。"),
W("sofa","名","ソファ","Soft sofa.","ふわふわソファ。"),
W("bed","名","ベッド","Soft bed.","ふわふわベッド。"),
W("blanket","名","もうふ","Warm blanket.","あたたかいもうふ。"),
W("pillow","名","まくら","Soft pillow.","やわらかいまくら。"),
W("towel","名","タオル","Clean towel.","きれいなタオル。"),
W("soap","名","せっけん","Wash with soap.","せっけんであらう。"),
W("fork","名","フォーク","Use a fork.","フォークをつかう。"),
W("spoon","名","スプーン","Big spoon.","おおきなスプーン。"),
W("knife","名","ナイフ","Sharp knife.","するどいナイフ。"),
W("dish","名","おさら","Wash dishes.","おさらをあらう。"),
W("plate","名","プレート","Dinner plate.","ばんごはん用のさら。"),
W("cup","名","コップ","Coffee cup.","コーヒーカップ。"),
W("glass","名","コップ(ガラス)","Glass of water.","コップ1ぱいの水。"),
W("bottle","名","びん","Empty bottle.","からのびん。"),
W("bag","名","かばん","School bag.","ランドセル。"),
W("box","名","はこ","Big box.","おおきなはこ。"),
W("basket","名","かご","Picnic basket.","ピクニックかご。"),
W("umbrella","名","かさ","Open umbrella.","かさをひらく。"),
W("hat","名","ぼうし","Red hat.","あかいぼうし。"),
W("cap","名","ぼうし(つば付)","Baseball cap.","やきゅうのぼうし。"),
W("shoe","名","くつ","New shoes.","あたらしいくつ。"),
W("sock","名","くつした","Warm sock.","あたたかいくつした。"),
W("shirt","名","シャツ","White shirt.","しろいシャツ。"),
W("pants","名","ズボン","Long pants.","ながいズボン。"),
W("dress","名","ドレス","Pretty dress.","きれいなドレス。"),
W("coat","名","コート","Winter coat.","ふゆのコート。"),
W("jacket","名","ジャケット","Light jacket.","かるいジャケット。"),
]))

# ===== Day 19: 名詞: 体・健康・気持ち =====
DAYS.append(("名詞: 体・健康・気持ち", [
W("body","名","からだ","Healthy body.","けんこうなからだ。"),
W("head","名","あたま","Hit my head.","あたまをぶつけた。"),
W("face","名","かお","Round face.","まるい顔。"),
W("hair","名","かみ","Long hair.","ながいかみ。"),
W("eye","名","め","Big eyes.","おおきいめ。"),
W("nose","名","はな","Cute nose.","かわいいはな。"),
W("mouth","名","くち","Open mouth.","くちをあけて。"),
W("ear","名","みみ","Big ear.","おおきいみみ。"),
W("teeth","名","は","White teeth.","しろいは。"),
W("tongue","名","した","Pink tongue.","ピンクのした。"),
W("neck","名","くび","Long neck.","ながいくび。"),
W("shoulder","名","かた","Sore shoulder.","かたがいたい。"),
W("arm","名","うで","Strong arm.","つよいうで。"),
W("hand","名","て","Wash hand.","てをあらう。"),
W("finger","名","ゆび","Small finger.","ちいさいゆび。"),
W("leg","名","あし","Long leg.","ながいあし。"),
W("foot","名","あし(足首から下)","Sore foot.","あしがいたい。"),
W("knee","名","ひざ","Hurt knee.","ひざをけが。"),
W("toe","名","つまさき","Toe pain.","つまさきがいたい。"),
W("stomach","名","おなか","Stomachache.","おなかがいたい。"),
W("heart","名","こころ/しんぞう","Kind heart.","やさしいこころ。"),
W("brain","名","のう","Smart brain.","かしこいのう。"),
W("blood","名","ち","Red blood.","あかいち。"),
W("bone","名","ほね","Strong bone.","つよいほね。"),
W("skin","名","はだ","Soft skin.","やわらかいはだ。"),
W("muscle","名","きんにく","Strong muscle.","つよいきんにく。"),
W("health","名","けんこう","Good health.","けんこう。"),
W("medicine","名","くすり","Take medicine.","くすりをのむ。"),
W("disease","名","びょうき","Serious disease.","じゅうとくなびょうき。"),
W("fever","名","ねつ","High fever.","こうねつ。"),
W("cold","名","かぜ","Catch a cold.","かぜをひく。"),
W("flu","名","インフル","Flu shot.","インフルワクチン。"),
W("headache","名","ずつう","Bad headache.","ひどいずつう。"),
W("pain","名","いたみ","Sharp pain.","するどいいたみ。"),
W("injury","名","けが","Minor injury.","ちょっとしたけが。"),
W("happiness","名","しあわせ","True happiness.","ほんとうのしあわせ。"),
W("sadness","名","かなしみ","Deep sadness.","ふかいかなしみ。"),
W("anger","名","いかり","Hide anger.","いかりをかくす。"),
W("fear","名","おそれ","Face fear.","おそれをのりこえる。"),
W("love","名","あい","True love.","ほんとうのあい。"),
W("hope","名","きぼう","New hope.","あたらしいきぼう。"),
W("worry","名","しんぱい","No worry.","しんぱいなし。"),
W("smile","名","えがお","Big smile.","おおきなえがお。"),
W("laugh","名","わらい","Loud laugh.","おおきなわらい。"),
W("dream","名","ゆめ","Sweet dream.","いいゆめ。"),
]))

# ===== Day 20: 熟語・句動詞① =====
DAYS.append(("熟語・句どうし ①", [
W("a lot of","句","たくさんの","A lot of fun.","たくさんのたのしみ。"),
W("each other","句","おたがい","Help each other.","たがいに助け合う。"),
W("for example","句","たとえば","For example, apples.","たとえばりんご。"),
W("in front of","句","のまえに","In front of the door.","ドアのまえ。"),
W("look for","句","さがす","Look for the key.","かぎをさがす。"),
W("look forward to","句","たのしみにする","Look forward to it.","たのしみ。"),
W("take care of","句","せわをする","Take care of the dog.","犬のせわ。"),
W("be good at","句","がじょうずだ","Good at math.","さんすうがとくい。"),
W("be interested in","句","にきょうみがある","Interested in space.","うちゅうにきょうみ。"),
W("have to","句","しなくてはいけない","I have to go.","行かなきゃ。"),
W("according to","句","によると","According to news.","ニュースによると。"),
W("as soon as","句","するとすぐに","As soon as I came.","つくとすぐに。"),
W("because of","句","のせいで","Because of rain.","あめのせいで。"),
W("by the way","句","ところで","By the way, hi.","ところでやあ。"),
W("give up","句","あきらめる","Don't give up.","あきらめないで。"),
W("grow up","句","せいちょうする","Grew up here.","ここでそだった。"),
W("put on","句","身につける","Put on your hat.","ぼうしをかぶる。"),
W("take off","句","ぬぐ/はなれる","Take off shoes.","くつをぬぐ。"),
W("turn on","句","スイッチを入れる","Turn on the light.","でんきをつけて。"),
W("turn off","句","スイッチを切る","Turn off TV.","テレビをけして。"),
W("get up","句","おきる","Get up early.","はやくおきる。"),
W("go to bed","句","ねる","Go to bed.","ねる。"),
W("stand up","句","たつ","Stand up.","たって。"),
W("sit down","句","すわる","Sit down.","すわって。"),
W("come back","句","もどる","Come back soon.","すぐにもどる。"),
W("go out","句","でかける","Go out today.","きょうはでかける。"),
W("hurry up","句","いそぐ","Hurry up!","いそいで！"),
W("wake up","句","おきる","Wake up!","おきて！"),
W("look at","句","見る","Look at this.","これを見て。"),
W("listen to","句","きく","Listen to music.","おんがくをきく。"),
W("talk to","句","はなす","Talk to me.","はなしかけて。"),
W("write to","句","てがみをかく","Write to me.","てがみをかいてね。"),
W("wait for","句","まつ","Wait for me.","まってて。"),
W("ask for","句","たのむ","Ask for help.","たすけをたのむ。"),
W("pay for","句","しはらう","Pay for lunch.","ランチだい。"),
W("look like","句","ににている","Looks like rain.","あめがふりそう。"),
W("feel like","句","したいきぶん","Feel like sleeping.","ねむい。"),
W("be afraid of","句","をこわがる","Afraid of dogs.","犬がこわい。"),
W("be tired of","句","あきる","Tired of rain.","あめにあきた。"),
W("be famous for","句","でゆうめい","Famous for sushi.","すしでゆうめい。"),
W("be late for","句","におくれる","Late for school.","学校におくれる。"),
W("be ready for","句","のじゅんびOK","Ready for the test.","テストのじゅんびOK。"),
W("be proud of","句","をほこりにする","Proud of you.","あなたがじまん。"),
W("instead of","句","のかわりに","Tea instead of coffee.","コーヒーじゃなくおちゃ。"),
W("at first","句","さいしょは","Hard at first.","さいしょはたいへん。"),
]))

# ===== Day 21: 熟語・句動詞② =====
DAYS.append(("熟語・句どうし ②", [
W("at last","句","ついに","At last, done!","ついにかんせい。"),
W("at least","句","すくなくとも","At least 5.","すくなくとも5。"),
W("at most","句","せいぜい","At most 10.","せいぜい10。"),
W("after all","句","けっきょく","After all, fun.","けっきょくたのしい。"),
W("all day","句","いちにちじゅう","Played all day.","一日中あそんだ。"),
W("all the time","句","ずっと","Smile all the time.","ずっとえがお。"),
W("all over","句","じゅう","All over Japan.","にほんじゅう。"),
W("right now","句","いますぐ","Do it right now.","いますぐやって。"),
W("right away","句","すぐに","Reply right away.","すぐへんじして。"),
W("over there","句","あそこに","Over there.","あそこ。"),
W("for the first time","句","はじめて","For the first time.","はじめて。"),
W("a few","句","すこし","A few minutes.","すこし。"),
W("a little","句","ちょっと","A little salt.","しおをすこし。"),
W("a kind of","句","のいっしゅ","A kind of game.","ゲームのいっしゅ。"),
W("a piece of","句","ひときれの","A piece of cake.","ケーキひときれ。"),
W("a couple of","句","2〜3の","A couple of days.","2,3日。"),
W("such as","句","のような","Sports such as soccer.","サッカーなどのスポーツ。"),
W("most of","句","のたいてい","Most of the time.","たいてい。"),
W("some of","句","のなかには","Some of them.","それらのなかの一部。"),
W("plenty of","句","たくさんの","Plenty of food.","たくさんの食料。"),
W("a number of","句","いくつかの","A number of cars.","なんだいかの車。"),
W("be used to","句","になれる","Used to noise.","おとになれる。"),
W("used to","句","かつて〜した","I used to swim.","むかしはおよいだ。"),
W("had better","句","のほうがよい","Better stay.","とどまったほうがいい。"),
W("would like","句","がほしい","Would like tea.","おちゃがほしい。"),
W("would like to","句","したい","Like to go.","行きたい。"),
W("had to","句","しなければならなかった","Had to go.","行かなくてはいけなかった。"),
W("be able to","句","できる","Able to swim.","およげる。"),
W("be going to","句","する予定","Going to study.","べんきょうするよてい。"),
W("would rather","句","のほうがいい","Rather stay home.","家にいたほうがいい。"),
W("not only","句","だけでなく","Not only kids.","こどもだけじゃない。"),
W("both of","句","のどちらも","Both of us.","わたしたちの両方。"),
W("either of","句","どちらか","Either of them.","どちらか一方。"),
W("neither of","句","どちらも〜ない","Neither of them.","どちらも〜ない。"),
W("not yet","句","まだ","Not yet done.","まだ。"),
W("no longer","句","もはや〜ない","No longer young.","もうわかくない。"),
W("in time","句","まにあう","In time for class.","じゅぎょうにまにあう。"),
W("on time","句","じかんどおり","On time, please.","じかんどおりに。"),
W("be supposed to","句","のはずだ","Supposed to come.","くるはず。"),
W("get along with","句","なかよくする","Get along with him.","なかよくする。"),
W("look up","句","しらべる","Look up the word.","ことばをしらべる。"),
W("look out","句","気をつけて","Look out!","あぶない！"),
W("look after","句","せわをする","Look after the cat.","ねこのせわ。"),
W("come from","句","しゅっしんは","I come from Japan.","にほんしゅっしん。"),
W("be made of","句","でつくられる","Made of wood.","木でできてる。"),
]))

# ===== Day 22: そうふくしゅう（高ひんしゅつ＆応用） =====
DAYS.append(("総ふくしゅう・応用", [
W("information","名","じょうほう","More info, please.","もっとじょうほう。"),
W("experience","名","けいけん","New experience.","あたらしいけいけん。"),
W("chance","名","きかい","Last chance.","ラストチャンス。"),
W("problem","名","もんだい","Big problem.","おおきなもんだい。"),
W("reason","名","りゆう","Good reason.","ちゃんとしたりゆう。"),
W("trip","名","りょこう","Long trip.","ながいたび。"),
W("vacation","名","きゅうか","Summer vacation.","なつやすみ。"),
W("event","名","イベント","Big event.","おおきなイベント。"),
W("future","名","みらい","Bright future.","あかるいみらい。"),
W("world","名","せかい","Wide world.","ひろいせかい。"),
W("environment","名","かんきょう","Save environment.","かんきょうほご。"),
W("culture","名","ぶんか","Japanese culture.","にほんぶんか。"),
W("health","名","けんこう","Good health.","けんこう。"),
W("energy","名","エネルギー","Save energy.","エネルギーをせつやく。"),
W("recycle","動","リサイクルする","Recycle paper.","かみをリサイクル。"),
W("reduce","動","へらす","Reduce waste.","ごみをへらす。"),
W("increase","動","ふえる","Numbers increase.","ふえる。"),
W("however","副","しかしながら","However, it's hard.","しかしむずかしい。"),
W("although","接","だけれども","Although it rained.","あめだったけど。"),
W("instead","副","かわりに","Tea, instead.","かわりにおちゃ。"),
W("opportunity","名","チャンス","Great opportunity.","すばらしいチャンス。"),
W("knowledge","名","ちしき","Useful knowledge.","やくにたつちしき。"),
W("technology","名","ぎじゅつ","Modern technology.","げんだいぎじゅつ。"),
W("society","名","しゃかい","Modern society.","げんだいしゃかい。"),
W("government","名","せいふ","Strong government.","つよいせいふ。"),
W("university","名","だいがく","Big university.","おおきなだいがく。"),
W("education","名","きょういく","Good education.","いいきょういく。"),
W("communication","名","コミュニケーション","Daily communication.","にちじょうコミュニケーション。"),
W("relationship","名","かんけい","Good relationship.","よいかんけい。"),
W("development","名","はってん","Fast development.","はやいはってん。"),
W("solution","名","かいけつ","Quick solution.","はやいかいけつ。"),
W("decision","名","けってい","Big decision.","おおきなけってい。"),
W("argument","名","ぎろん","Heated argument.","あつい議論。"),
W("agreement","名","ごうい","Reach agreement.","ごういにいたる。"),
W("attitude","名","たいど","Positive attitude.","まえむきなたいど。"),
W("behavior","名","ふるまい","Good behavior.","いいふるまい。"),
W("ability","名","のうりょく","Great ability.","すごいのうりょく。"),
W("skill","名","スキル","Cooking skill.","りょうりのスキル。"),
W("effort","名","どりょく","Make effort.","どりょくする。"),
W("goal","名","もくひょう","Reach the goal.","ゴールにつく。"),
W("success","名","せいこう","Great success.","だいせいこう。"),
W("failure","名","しっぱい","Learn from failure.","しっぱいからまなぶ。"),
W("courage","名","ゆうき","Show courage.","ゆうきをだす。"),
W("patience","名","しんぼう","Need patience.","しんぼうがひつよう。"),
W("attention","名","ちゅうい","Pay attention.","ちゅういして。"),
]))

# Verify count: 22 days, target 45/day = 990
total = 0
for name, words in DAYS:
    total += len(words)
print(f"# total days={len(DAYS)} total words={total}", file=sys.stderr)
assert len(DAYS) == 22, f"days should be 22 not {len(DAYS)}"
for i,(name, words) in enumerate(DAYS):
    if len(words) != 45:
        print(f"# WARN: Day {i+1} '{name}' has {len(words)} words", file=sys.stderr)

# Output as JS array literal (UTF-8). Escape backticks/backslashes/dollar are not needed since we use JSON.
js_data = json.dumps([{"name":n,"words":w} for n,w in DAYS], ensure_ascii=False)
print("window.CURRICULUM = " + js_data + ";")
